WorldHealthOrganization/app

.github/workflows/client.yml, CONTRIBUTING.md
Closes #61 
Closes #62
Closes #71
=> Repo hygiene - CI build, dependency rules, enforce security audit

ONBOARDING.md, README.md
Very basic initial onboarding pointing to resources for new folks to get started.
Closes #101
=> Add basic ONBOARDING doc with basic getting started information

.github/workflows/preview.yaml
Set up a github action flow to automatically deploy a preview app.
Doing this in a main repo branch because that way we can test that it works before merging. (forks can't access secrets)
This PR sets up an automated preview at https://preview.whoapp.org.
During testing I ran it for every commit in a PR, in the last commit I configured it to only run for pushes to master.
=> Automatic preview

.github/workflows/client.yml
=> Use npm ci for github actions

CONTRIBUTING.md, ONBOARDING.md, README.md
Makes a few small tweaks to our docs from discussions on Slack today. Noting that we want to keep process lightweight, but also setting out guidelines that hopefully people will follow!
=> Update Onboarding and Contributing docs

docs/ONBOARDING.md, docs/ROADMAP.md
Creates a single place with version-controlled history to store updated thoughts on the product roadmap.
This first version is very much a WORK IN PROGRESS and we would like to get weigh-in from key folks across the different areas. The intention here is to just create that centralized place for when people are looking for what we are trying to accomplish.
N/A
N/A
=> Create WIP product roadmap

docs/CONTRIBUTING.md
=> Fix typo in CONTRIBUTING.md

client/ionic/src/components/Carousel.tsx
This will definitely require more design input in the future, but in the meantime, just make the font size smaller
Closes #235 
N/A
N/A
=> fix: make TextEmoji body text font size smaller

LICENSE
Just to make it easier to commit Pat's PR.
=> Update LICENSE for other WHO brand assets

content/credits.yaml
Jason and I helped build the Flutter app
=> Add new contributors

client/flutter/lib/home_page.dart
=> Use WHO-controlled domain for share button

docs/ONBOARDING.md
Docs should say that we are using flutter rather than ionic at the moment
=> Update to reflect Flutter usage

docs/ROADMAP.md
Some additional comments were submitted on #216 after it was merged. This PR addresses those comments
N/A
N/A
=> docs: Update Roadmap to PR feedback

docs/ONBOARDING.md
Steps to get flutter installed and client running
No
N/A
=> Flutter client setup in onboarding doc

client/flutter/analysis_options.yaml, client/flutter/pubspec.lock, client/flutter/pubspec.yaml
For #338 - enables Pedantic, which is Google’s recommended set of Dart static analysis settings - see https://medium.com/dartlang/pedantic-dart-1c7d365510de
Adds a development dependency to the pedantic package: https://pub.dev/packages/pedantic
I checked this enables the analysis by adding some code that violates the rules.
Also checked this PR currently causes no new compiler warnings.
=> Enable Pedantic static analysis rules

docs/ROADMAP.md
@hspinks will do a larger more detailed update later, just want a quick summary for the eng team pre-standup.
=> Brief ROADMAP update for v1.0 on March 30, 2020

docs/ONBOARDING.md, docs/README.md
=> [docs] Onboarding changes

client/flutter/.gitignore, client/flutter/pubspec.lock, client/flutter/pubspec.yaml, content/credits.yaml
The Dart SDK constraint should match Flutter **stable**. There is no benefit in not using the minimum constraint from stable.
With this PR, we will be able to use the latest stable Dart SDK features.
**No**.
Ran all existing tests.
=> Fix Dart SDK constraint

client/flutter/lib/carousel_page.dart, content/credits.yaml
This PR addresses two Dart analysis issues.
```
info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance
fields aren't final: CarouselView.pageController • lib/carousel_page.dart:48:7 • must_be_immutable
info • Unnecessary new keyword • lib/carousel_page.dart:55:35 • unnecessary_new
```
none
re-ran `flutter analyze` (and verified that the app still launched and ran)
=> fix two analysis issues

docs/ONBOARDING.md
Update our onboarding docs to reflect the growth of the project
N/A
N/A
=> [docs] update onboarding, Slack status, and team leads

client/flutter/lib/home_page.dart, client/flutter/pubspec.lock
Changes Home Page layout
Added a staggered grid view layout.
flutter_staggered_grid_view: ^0.3.0
I ran the app on physical android device with no issues.
=> Changed Home Page

.github/workflows/flutter-build.yml
Bruno/Sam please *do not* approve this change.
@hspinks plz try again =D
=> Test CODEOWNERS again

.github/issue_template.md
Adds an issue template with a checklist to hopefully prevent duplicate issues
N/A
N/A
=> [chore] Create issue template

client/flutter/lib/pages/home_page.dart
Removes non-functional button for v1.
=> [fix] Remove App Feedback, closes #493

.github/pull_request_template.md
Purpose: This allows the team to do a thoughtful triage (priorities, punt, etc.) prior to work being done.
=> [docs] Require assigned issues for PR

client/flutter/lib/components/page_button.dart, client/flutter/lib/components/page_scaffold.dart, client/flutter/lib/pages/home_page.dart, client/flutter/lib/pages/onboarding/permission_request_page.dart, client/flutter/lib/pages/question_index.dart
- Update Homepage styling
- Added donate button and app version notes at bottom
- created pageScaffold class
No
iOS simulator
=> Updated homepage styling

client/flutter/android/app/build.gradle, client/flutter/android/build.gradle, client/flutter/lib/constants.dart, client/flutter/lib/main.dart, client/flutter/lib/pages/home_page.dart, client/flutter/pubspec.yaml, content/credits.yaml
This reverts commit 6261230bda701593fa51d28d0c5427110fccaec1.
=> Revert "Add Firebase Analytics (#512)"

client/flutter/lib/pages/home_page.dart, client/flutter/lib/pages/onboarding/legal_landing_page.dart, client/flutter/lib/pages/onboarding/location_sharing_page.dart, client/flutter/lib/pages/onboarding/notifications_page.dart, client/flutter/lib/pages/onboarding/permission_request_page.dart
Finishes onboarding flow
- Added legal page
- Added images to location and notification pages
Resolves #575 #574 #573 #572
No
iOS simulator
=> Finished Onboarding Slide

client/flutter/assets/content_bundles/your_questions_answered.en.yaml
=> Fix typo in question title

client/flutter/lib/api/content_loading.dart
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
=> [fix] Request header should be Accept

client/flutter/lib/pages/home_page.dart
Remove space in "corona virus" in the title. I know we'll probably
localize this soon, but just wanted to fix this in the meantime.
=> Remove space in "corona virus"

client/flutter/lib/pages/home_page.dart, client/flutter/lib/pages/onboarding/legal_landing_page.dart, client/flutter/lib/pages/onboarding/location_sharing_page.dart, client/flutter/lib/pages/onboarding/notifications_page.dart, client/flutter/lib/pages/onboarding/onboarding_page.dart
Gives onboarding screens a fluid animation
No
iOS Simulator
Here it is in the middle of an animation:
=> Onboarding screen new progress

client/flutter/lib/pages/question_index.dart
=> Remove stale comments and format.

client/flutter/lib/api/user_preferences.dart, client/flutter/pubspec.lock, client/flutter/pubspec.yaml
=> Add client uuid generated on first use.

server/appengine/src/main/java/who/AppStoreServlet.java, server/appengine/src/main/java/who/ClientInterceptor.java, server/appengine/src/main/java/who/WhoServletModule.java
=> Add /app trampoline. Make header parsing more robust.

client/flutter/lib/components/page_header.dart
Closes https://github.com/WorldHealthOrganization/app/issues/679
No
=> fix: use IconButton for page header back arrow

client/flutter/lib/pages/onboarding/permission_request_page.dart
Matches app layout to the Figma layout.
Change static text size to a textScaleFactor
#682 
No
Tested on physical Galaxy S10 device.
=> Onboarding notifications page

client/flutter/lib/pages/protect_yourself.dart
Matches Protect Yourself page to Figma's
Changed font weight of header
#691
No
Tested on physical Galaxy S10
=> Changed header weight

client/flutter/lib/pages/travel_advice.dart
Updated the header's color and the list item's color.
#695
No
Tested on physical android device.
=> Updated Travel Advice colors

client/flutter/assets/content_bundles/your_questions_answered.en.yaml
- [ X] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here: https://github.com/WorldHealthOrganization/app/issues/702
- [X ] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [ X] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ X] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [X ] Verified your name is in the …
=> fixed typos and added missing question

client/flutter/assets/credits.yaml, client/flutter/lib/pages/about_page.dart, client/flutter/lib/pages/home_page.dart, content/credits.yaml
No design mocks.  Credits organization approved by strategy team.
=> [feat] Implement About page

client/flutter/assets/content_bundles/your_questions_answered.en.yaml
Removes the duplicate question "What are the treatment options for COVID-19?" from the Q&A screen
N/A
N/A
=> [content] Remove duplicate question from Your Questions Answered screen

.gitattributes
Sorry I was too slow with the comment on https://github.com/WorldHealthOrganization/app/pull/595#discussion_r399914243
=> Vendor out the Google S2 code

content/credits.yaml
- [ X] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [ X] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ X] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).
=> Add Lingo24 team to credits

client/flutter/lib/components/page_button.dart, client/flutter/lib/pages/home_page.dart
Updated HomePage UI
Changed text sizes and colors, as well as some icon colors.
Closes #687
No
Tested on physical Galaxy S10.
=> Update HomePage tile text style

client/flutter/lib/pages/question_index.dart
Styles questions to match fimga
No
iOS simulator
=> Updated question page UI

client/flutter/lib/api/who_service.dart, client/flutter/lib/pages/home_page.dart, client/flutter/lib/pages/latest_numbers.dart
Closes #521 
Someone else will have to make it look nice.
Stats from our server.
TODO: Caching
=> [feat] Latest Numbers page

client/flutter/lib/components/page_button.dart, client/flutter/lib/pages/home_page.dart
In progress - fixing critical UI issues before cutting next RC
N/A
TBD
=> Fix overflow in Main screen tiles

client/flutter/lib/components/page_scaffold/page_header.dart
removes hidden icon button that defaults on app bars
iOS simulator
Before:
=> hidden back button gone

client/flutter/lib/generated/intl/messages_en.dart, client/flutter/lib/generated/intl/messages_en_US.dart, client/flutter/lib/generated/l10n.dart, client/flutter/lib/l10n/intl_en_US.arb, client/flutter/lib/pages/latest_numbers.dart
Extracted the latest hard coded strings added in  latest_numbers.dart
No
Simulator
=> Localized latest_numbers.dart

client/flutter/lib/components/page_scaffold/page_header.dart
Reintroduces the InkSplash to the back arrow in the page header component.
A regression in https://github.com/WorldHealthOrganization/app/pull/746 caused it to be removed.
No
Running the app and tapping the back arrow button
=> fix: fixes the page header ink splash

client/flutter/lib/main.dart, client/flutter/lib/pages/question_index.dart, content/credits.yaml
[#756 ](https://github.com/WorldHealthOrganization/app/issues/756)
In questions_index.dart for both the Questions and the Get the Facts (fka Mythbusters) pages:
SF Pro Text is not in project. if you want to add it for all the text in the project for iOS before v1.0.0, I can make a pull request. It is a simple change in ThemeData .
=> P0 - Update question-answer accordion styles #756

client/flutter/lib/components/page_button.dart, client/flutter/lib/pages/home_page.dart
- Closes https://github.com/WorldHealthOrganization/app/issues/750
- Sets the card tile border-radius to 16 on the home page
- Add white background to buttons at the bottom of the home page
- Changes the arrow color to #C9CDD6 on the arrows at the bottom of the home page
=> fix: update home page card shape and bottom menu theme

client/flutter/lib/pages/onboarding/location_sharing_page.dart, content/credits.yaml
Only reproducible if Location Services is Off. 
This will fix a bug where the users is not forwarded to the home page after clicking the "Allow Location Sharing" button in onboarding page. This will also fix the crash when clicking "No Thanks" in the location service request popup.
No
Tested with Location Services turned off using devices below:
Pixel - Android 7.0
Redmi Note2 - Android 5.1
No Response after clicking ok issue: …
=> Fix: app not showing the home page after allowing onboard location

client/flutter/lib/components/page_scaffold/page_header.dart
Fix ui problems in global header 
Fixes [#749](https://github.com/WorldHealthOrganization/app/issues/749)
+ Fix bug when large text where overflowing.
No
NOW:
<image height="400" src="https://user-images.githubusercontent.com/19904063/78176317-90994b00-745c-11ea-9035-fe8bec379388.PNG"/>
BEFORE:
<image height="400" src="https://user-images.githubusercontent.com/19904063/78176639-19b08200-745d-11ea-908a-19bc634ed099.PNG"/>
=> P0 #749 - Global header - design review feedback

content/credits.yaml
for native speaker review of French translations for v1
=> Add Maxime Cheminade

server/appengine/src/main/webapp/content/bundles
=> Add content symlink

server/appengine/src/main/java/who/Environment.java, server/bin/deploy-hackerone.sh
=> Add hacker one deployment

client/flutter/android/app/build.gradle, content/credits.yaml
Removes hard-coded version numbers from the Android `build.gradle` file so that the values from `local.properties` (propagated from `pubspec.yaml`) are used
fixes https://github.com/WorldHealthOrganization/app/issues/837
no
Yes. In a local build
=> remove hardcoded version from Android build.gradle

client/flutter/android/app/build.gradle, client/flutter/ios/Runner/Info.plist, content/credits.yaml
Changes location permission description text
Relevant values in Info.plist file are changed
This PR closes issue "Set iOS system permission dialog explanation text" #824
No
=> fix: location permission description text changed

client/flutter/lib/components/news_feed_item.dart
Updates news arrow to be same color as Figma design
No
iOS simulator
Before:
After:
=> Updated forward icon button to match figma

client/flutter/lib/pages/home_page.dart
Does what it says ~~on the can~~ in the title
No
=> fix: add missing anatlyics logs to home page

client/flutter/lib/components/page_scaffold/page_header.dart
Adds bottom line to app bar to match Figma
No
Before:
After:
=> Add bottom line to app bar to match figma

client/flutter/lib/components/arrow_button.dart, client/flutter/lib/pages/latest_numbers.dart
=> Latest numbers theme

client/flutter/lib/pages/question_index.dart
Closes https://github.com/WorldHealthOrganization/app/issues/860
Opening and closing the facts and questions page to verify the crash no longer occurs.
=> fix: prevent setState invokation after disposal in question_index.dart

client/flutter/ios/Runner/Info.plist, content/credits.yaml
Setting `ITSAppUsesNonExemptEncryption` to `false` in Info.plist to prevent TestFlight / App Store from always asking (and preventing _fastlane_ from submitting)
Part of #318 
Complements https://github.com/WorldHealthOrganization/app/pull/405#discussion_r403691635
Nope nope
Opened up Xcode 😊
=> Setting ITSAppUsesNonExemptEncryption to false in Info.plist to preve nt TestFlight / App Store from always asking

client/flutter/lib/pages/home_page.dart, client/flutter/pubspec.lock, client/flutter/pubspec.yaml
- Closes https://github.com/WorldHealthOrganization/app/issues/884
- Closes https://github.com/WorldHealthOrganization/app/issues/785
- Allows all of the buttons in the HomePage grid to grow to prevent overflows
- Adjusts the height ratio of the "Latest Numbers" and "Questions & Answers" buttons to match the Figma design.
- Cleans up the syntax of the buttons in the HomePage grid fortunately/unfortunately
I removed …
=> P0 fix: allow home page grid buttons to grow

client/flutter/lib/pages/onboarding/location_sharing_page.dart
Closes https://github.com/WorldHealthOrganization/app/issues/915 , more details in the issue.
No
Trying every scenario e.g. grant permission but keep GPS off then verifying that the location was still being retrieved and used.
=> fix: complete onboarding before fetching location

client/flutter/lib/api/content_bundle.dart, client/flutter/lib/api/content_loading.dart, client/flutter/lib/api/who_service.dart
This PR changes the content bundle loading to always interpret the network loaded file as UTF-8, regardless of the server configuration.
=> Always interpret content bundle as UTF-8.

.github/CODEOWNERS
Much easier for us to fix build issues.
=> Since no PROD secrets shall be configured in this repo, add me/hunter to full owners

client/flutter/lib/components/news_feed_item.dart
The PR I created last night introduced a regression https://github.com/WorldHealthOrganization/app/pull/922
Subheadings on the news feed page shouldn't be centered. This change provides the text widget with the full width so it's aligned to the edge for RTL and LTR layouts.
The moral is, don't send in PRs at 1am.
No
Running the app on my Android device.
=> fix: Realign news feed headings to start

client/flutter/ios/Runner/Info.plist
=> COVID en dash 19

client/flutter/lib/pages/settings_page.dart
- Closes https://github.com/WorldHealthOrganization/app/issues/926
- TalkBack now reads "**Ticked/Not Ticked** Analytics, Allow WHO to collect analytics for product improvement using Google Analytics **switch, double-tap to toggle**"
- Wrap the whole section in an InkWell
No
Using TalkBack on my Android device
=> fix: add semantics to settings page analytics switch

api/who/who.proto
=> Latest Numbers timeseries data struct

server/appengine/src/main/java/who/RefreshCaseStatsServlet.java, server/appengine/src/main/java/who/StoredCaseStats.java
Closes #961 
Total data is <10k - not bad.  After gzip it is 2kb.
=> [feat] Provide global case stats timeseries

client/flutter/lib/components/latest_numbers_graph.dart, client/flutter/lib/pages/latest_numbers.dart, client/flutter/pubspec.lock, client/flutter/pubspec.yaml
Adds a graph of daily cases and deaths to the client app.
TODOs:
* Fix the graph animation so that the motion of the line animates up from the axis as opposed to from side to side
* Account for the possibility that there is not exactly 1 snapshot per 24 hour period
* Figure out if https://github.com/WorldHealthOrganization/app/pull/972/commits/cb85d50103160c8bc3b5c1a8a7ecbdb5e6cd2ecd#diff-fb3eeb09042e7a2b832bcb8a90cbacc7R84 is the right way to actually do this
Closes #960 
* [`fl_chart`](https://pub.dev/packages/fl_chart): verified developer, BSD license, 160 likes on pub.dev, only dependency written by Mr. @dnfield 😄
<details>
<summary>Screenshot</summary>
</details>
=> [feat] Add graph to Latest Numbers page

client/flutter/assets/content_bundles/get_the_facts.en.yaml, client/flutter/lib/components/carousel.dart, client/flutter/lib/pages/facts_carousel_page.dart
Update to David's "bold colors" scheme from Figma.
#956
=> [feat] Tweaks / formatting for Get the Facts

client/flutter/assets/svg/placeholder.svg, client/flutter/assets/svg/x-priv-bathroom-hair-dryer.svg, client/flutter/assets/svg/x-priv-bathroom-tub-towel.svg, client/flutter/assets/svg/x-priv-ceiling-lamp-1.svg, client/flutter/assets/svg/x-priv-christmas-snow.svg, client/flutter/assets/svg/x-priv-disability-cane.svg, client/flutter/assets/svg/x-priv-drugs-box.svg, client/flutter/assets/svg/x-priv-drugs-pills-box.svg, client/flutter/assets/svg/x-priv-face-id-scan-1.svg, client/flutter/assets/svg/x-priv-flying-insect-dragonfly.svg, client/flutter/assets/svg/x-priv-gardening-sprinkle-bottle.svg, client/flutter/assets/svg/x-priv-kitchenware-garlic-mincer.svg, client/flutter/assets/svg/x-priv-medical-instrument-syringe.svg, client/flutter/assets/svg/x-priv-medical-specialty-breathing.svg, client/flutter/assets/svg/x-priv-temperature-thermometer-high.svg
It adds a placeholder svg and symlinks to that placeholder for all private assets.
This will allow people building the app from this repo to get a fully functional app actual assets instead of errors in their console.
No
Local build & emulator.
=> Placeholder for private assets

client/flutter/lib/pages/home_page.dart
https://github.com/WorldHealthOrganization/app/issues/911#issuecomment-612489934
https://github.com/WorldHealthOrganization/app/pull/992 changed the padding around the grid buttons on the home page([change](https://github.com/WorldHealthOrganization/app/pull/992/files#diff-6ac3b48a3508990c0e66b302adaefdc0L204)) causing https://github.com/WorldHealthOrganization/app/issues/911#issuecomment-612422593 
No
Running on my Android device.
=> fix: decrease horizontal padding on home page

client/flutter/lib/api/content/content_loading.dart, client/flutter/lib/api/who_service.dart
=> [feat] Add user agent and accept gzip encoding, closes #976

client/flutter/ios/Runner/Info.plist
companion to https://github.com/WorldHealthOrganization/app/pull/1036
Together, they close Issue #1012
=> Remove French from info.plist

client/flutter/lib/components/carousel/carousel.dart
Added chevrons to app Get the Facts page
Closes #999
No
iOS simulator
=> added chevrons

server/README.md, server/appengine/src/main/java/who/Environment.java, server/appengine/src/main/webapp/WEB-INF/web.xml, server/appengine/src/main/webapp/placeholder.html, server/bin/deploy-production.sh
- Move production server and data to Europe
- Document our Google Cloud layout
- Minor web.xml cleanup
=> Move production data to Europe.

client/flutter/assets/credits.yaml, docs/MULTIREPO.md
This seems like a good place to discuss, please use source code comments to start threads about specific points!
=> [draft] Multi-repo flow

.github/issue_template.md, .github/pull_request_template.md
This PR does a very quick pass over our issue and PR templates, making a couple of quick changes:
* Moves the checklist to the bottom of the comment
* Seeing all of our PRs and Issues starting with an identical block of text makes it harder to immediately see at a glance where the description is. PRs should start with the relevant info
* Comments out the dependencies & tests sections by default for authors to uncomment when needed
* We have tons of PRs where we just have the section titles and no content in the sections... hoping this makes things more readable
* Adds a screenshots section with an expander
* If there are lots of screenshots, the PR comment can take a lot of vertical space, making things less readable... hiding the screenshots by default but allowing a reviewer to expand …
=> [chore] Update issue and PR templates

docs/README.md
=> homepage typo

client/flutter/lib/generated/intl/messages_all.dart, client/flutter/lib/generated/intl/messages_en.dart, client/flutter/lib/generated/intl/messages_en_US.dart, client/flutter/lib/generated/l10n.dart, client/flutter/lib/l10n/intl_en_US.arb, client/flutter/lib/pages/latest_numbers.dart
Localize source string on Latest Numbers screen
Closes #1047 
No
iOS simulator
=> Issue 1047 Localize source string on Latest Numbers screen

client/flutter/README.md, dev-setup.sh, docs/ONBOARDING.md, tools/.huskyrc.json, tools/.lintstagedrc.json, tools/package-lock.json, tools/package.json, tools/verify-client.sh, tools/verify-server.sh
Client will be formatted, analyzed, and tested
Server will be tested
After this, all devs must run `./dev-setup.sh` once.
TESTED= I cloned this PR branch and tried to break the client and server, and it would not let me.
Closes #1092
=> Pre-commit hooks, closes #1092

client/flutter/assets/content_bundles/travel_advice.en.yaml, client/flutter/lib/api/content/schema/advice_content.dart, client/flutter/lib/constants.dart, client/flutter/lib/pages/travel_advice.dart, client/flutter/pubspec.lock, client/flutter/pubspec.yaml
closes #1128
Will need pixel perfect eventually, 
font awesome dependency, via flutter community official acct
Screenshot:
Mock:
=> Improve travel advice page; closes #1128

client/flutter/lib/components/learn_page_header.dart, client/flutter/lib/components/page_scaffold/page_scaffold.dart, client/flutter/lib/pages/main_pages/learn_page.dart
=> Learn page header

client/flutter/lib/main.dart
Closes https://github.com/WorldHealthOrganization/app/issues/1095
---
=> fix: allow crashlytics to function on first run

client/flutter/lib/components/home_page_header.dart
@britannio caught an unnecessary line in my header code. This PR removes that line.
=> Home page header delete unused line

LICENSE, client/flutter/lib/pages/license_page.dart
@theswerd will be turning this into a real license page, just needs the original file for now.
And client/flutter/lib/components/swipeable_open_container.dart was previously deleted :)
=> Add https://github.com/flutter/flutter/blob/fef2d6ccd6050298e498ea77a11d820aaeb4d087/packages/flutter/lib/src/material/about.dart

client/flutter/lib/components/page_scaffold/page_scaffold.dart, client/flutter/lib/pages/protect_yourself.dart, client/flutter/lib/pages/settings_page.dart, client/flutter/lib/pages/travel_advice.dart
The background on the Figma is a grey color, not a white color.
---
=> Update background color

client/flutter/assets/content_bundles/your_questions_answered.en.yaml
=> Don't repeat Question title

client/flutter/assets/content_bundles/home_index.en.yaml, client/flutter/lib/components/carousel/carousel.dart, client/flutter/lib/components/home_page_sections/home_page_donate.dart, client/flutter/lib/components/home_page_sections/home_page_header.dart, client/flutter/lib/components/home_page_sections/home_page_protect_yourself.dart, client/flutter/lib/components/home_page_sections/home_page_recent_numbers.dart, client/flutter/lib/pages/license_page.dart, client/flutter/lib/pages/main_pages/app_tab_router.dart, client/flutter/lib/pages/travel_advice.dart
Addressed a number of issues in real time with @davidkaneda in a design review. Additional tickets have been opened for items discussed in the review but not covered in this PR [here](https://github.com/WorldHealthOrganization/app/issues?q=is%3Aissue+is%3Aopen+label%3Aa%3Apixel-perfect+%22Design+Review%22+)
---
=> [feat] Design review tweaks

client/flutter/lib/pages/main_pages/learn_page.dart
Closes https://github.com/WorldHealthOrganization/app/issues/1248
Adding `fit: BoxFit.fitHeight` to the SVG is the main change but I had started by cleaning up the whole widget. Check the screenshots if there's any doubt.
<details>
Before: 
After:
</details>
---
=> fix: remove pixel gap from learn page card

client/flutter/lib/pages/settings_page.dart
Closes https://github.com/WorldHealthOrganization/app/issues/1251
Closes https://github.com/WorldHealthOrganization/app/issues/1252
<details>
Before Android:
After Android: 
</details>
---
=> refactor: Improve settings page switchItem component 

client/flutter/lib/components/page_scaffold/page_scaffold.dart, client/flutter/lib/main.dart, client/flutter/lib/pages/facts_carousel_page.dart, client/flutter/lib/pages/main_pages/app_tab_router.dart, client/flutter/lib/pages/onboarding/legal_landing_page.dart, client/flutter/lib/pages/onboarding/permission_request_page.dart, client/flutter/lib/pages/symptom_checker/symptom_checker_view.dart
Closes https://github.com/WorldHealthOrganization/app/issues/1227
The issue provides more details but I've replaced the `CupertinoApp` with a `MaterialApp`. Since we're still using a lot of Cupertino widgets like `CupertinoPageScaffold` I've had to wrap them in `Material` for the Text to render correctly.
---
=> fix: switch to material app and use platform scroll behaviour

client/flutter/lib/components/platform_widget.dart
Convenience widget for features like https://github.com/WorldHealthOrganization/app/issues/996. On Android it builds the `material` widget and on IOS it builds the `cupertino` widget.
Might require https://github.com/WorldHealthOrganization/app/pull/1225 to be merged first so `Theme.of(context)` can be accessed.
---
=> feature: Add platform widget

client/flutter/assets/content_bundles/symptom_checker.en.yaml, client/flutter/lib/api/content/schema/symptom_checker_content.dart, client/flutter/lib/components/forms.dart, client/flutter/lib/components/page_button.dart, client/flutter/lib/components/page_scaffold/page_header.dart, client/flutter/lib/components/page_scaffold/page_scaffold.dart, client/flutter/lib/constants.dart, client/flutter/lib/pages/symptom_checker/question_pages/previous_next_buttons.dart, client/flutter/lib/pages/symptom_checker/question_pages/short_list_question_view.dart, client/flutter/lib/pages/symptom_checker/symptom_checker_results_page.dart, client/flutter/lib/pages/symptom_checker/symptom_checker_view.dart
Closes #1101 Closes #1102 Closes #1108 
TODO outside of this PR:
- Intro screen #1112 
- Assign all the right icons to the result cards (will file new issue)
- Redo the headers (Britannio doing in other PR). - so I've ignored the janky headers here
- Add a WillPopScope to make the back buttons show previous question in the PageController (will file issue)
=> Symptom Checker UI

client/flutter/lib/pages/settings_page.dart
Closes #1253 
<details>
</details>
---
=> [feat] Ensure settings description doesn't wrap

client/flutter/android/app/src/main/AndroidManifest.xml
=> Disable auto backup closes #1170

client/flutter/lib/pages/symptom_checker/question_pages/short_list_question_view.dart, client/flutter/lib/pages/symptom_checker/symptom_checker_view.dart
Closes https://github.com/WorldHealthOrganization/app/issues/1295
Tapping the back button or pressing the back button on Android will now transition to the previous options page and going back from the results page will bring you back to the home page.
---
=> fix: add WillPopScope to symptom checker

client/flutter/lib/components/page_scaffold/page_header.dart
=> fix: show trailing widget in PageHeader

client/flutter/lib/components/recent_numbers_graph.dart, client/flutter/lib/pages/main_pages/recent_numbers.dart
Styles the stats graph to match the Figma.
!
=> styled graphs

server/appengine/src/main/java/who/WhoServletModule.java
Closes #1327
http://localhost:8080/content/bundles/your_questions_answered.en_US.yaml
http://localhost:8080/content/bundles/your_questions_answered.en_FR.yaml
http://localhost:8080/content/bundles/your_questions_answered.en_KR.yaml
etc.
=> Serve all country asset bundles from server

client/flutter/assets/content_bundles/get_the_facts.en.yaml, client/flutter/assets/content_bundles/home_index.en.yaml, client/flutter/lib/components/home_page_sections/home_page_information_card.dart
=> [feat] Add images to get the facts page and homepage information card

client/flutter/lib/api/content/content_bundle.dart, client/flutter/lib/api/content/content_loading.dart, client/flutter/lib/api/user_preferences.dart, client/flutter/lib/components/home_page_sections/home_page_protect_yourself.dart, client/flutter/lib/main.dart, client/flutter/lib/pages/onboarding/onboarding_page.dart, client/flutter/lib/pages/symptom_checker/symptom_checker_view.dart
This PR introduces pre-caching of common content bundles upon acceptance of the terms of service and also upon subsequent app launches or returning to the foreground.
=> Pre-cache content bundles.

client/flutter/pubspec.yaml
Keeping `master` pubspec.yaml version in sync with releases...
=> Bump app version to `0.11.0+20-git`

client/flutter/lib/components/page_scaffold/page_header.dart
=> 🦚 fix: app bar should be pinned in scroll; closes #1349

client/flutter/assets/content_bundles/symptom_checker.en.yaml, client/flutter/assets/svg/x-priv-bathroom-hair-dryer.svg, client/flutter/assets/svg/x-priv-bathroom-tub-towel.svg, client/flutter/assets/svg/x-priv-ceiling-lamp-1.svg, client/flutter/assets/svg/x-priv-christmas-snow.svg, client/flutter/assets/svg/x-priv-disability-cane.svg, client/flutter/assets/svg/x-priv-drugs-box.svg, client/flutter/assets/svg/x-priv-drugs-pills-box.svg, client/flutter/assets/svg/x-priv-face-id-scan-1.svg, client/flutter/assets/svg/x-priv-flying-insect-dragonfly.svg, client/flutter/assets/svg/x-priv-gardening-sprinkle-bottle.svg, client/flutter/assets/svg/x-priv-kitchenware-garlic-mincer.svg, client/flutter/assets/svg/x-priv-medical-instrument-syringe.svg, client/flutter/assets/svg/x-priv-medical-specialty-breathing.svg, client/flutter/assets/svg/x-priv-temperature-thermometer-high.svg, client/flutter/lib/api/content/schema/symptom_checker_content.dart, client/flutter/lib/components/menu_list_tile.dart, client/flutter/lib/pages/main_pages/check_up_intro_page.dart, client/flutter/lib/pages/symptom_checker/symptom_checker_results_page.dart
* Add icons to result cards
* Add a Cancel button to question screens
* Add theme links to masks card
* Add tiny link to protect yourself in blue
* Hitting back on results should go back to last answer
Closes #1331
=> 🌊🏖️ Symptom Checker UI fixes closes #1331

.github/CODEOWNERS
This PR removes me from the `CODEOWNERS` file.
---
=> Remove @sammousa from CODEOWNERS

.github/workflows/client-build.yaml
See https://flutter.dev/docs/deployment/cd#local-setup
=> CI should build release version of iOS

docs/README.md
This adds badges that tell someone looking at our project what languages and frameworks we use so they can immediately tell if they are able to contribute.
<details>
</details>
---
=> Update README.md with badges

LICENSE
Language from attorney Michael Nichols
=> ⚖️ Add agency mark text to License

.github/workflows/client.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/server.yaml
The workflow is mostly auto-generated by GitHub.
Also fixes the branch ref on client and server
=> CI: codeql-analysis.yml

client/flutter/lib/pages/settings_page.dart
Add the Issue number(s) assigned to you that this PR fully resolves, if any
Closes https://github.com/WorldHealthOrganization/app/issues/1427
---
=> open Github issue tracker when feedback button is tapped

api/who/who.proto, server/appengine/src/main/java/who/WhoServiceImpl.java
=> 📙 API for per-jurisdiction case stats

LICENSE
Legalese from attorney Michael Nichols
=> Update LICENSE for introduction of custom app icon

server/appengine/build.gradle
* Fix https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276
* Fix https://app.snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518
=> 👮 [Security] Upgrade server dependencies

api/who/who.proto
=> Update proto with feedback comments

client/flutter/lib/api/content/caching.dart, client/flutter/lib/api/content/content_loading.dart, client/flutter/lib/api/content/content_store.dart, client/flutter/lib/api/content/content_store.g.dart, client/flutter/lib/api/content/schema/advice_content.dart, client/flutter/lib/api/content/schema/conditional_content.dart, client/flutter/lib/api/content/schema/fact_content.dart, client/flutter/lib/api/content/schema/index_content.dart, client/flutter/lib/api/content/schema/question_content.dart, client/flutter/lib/api/content/schema/symptom_checker_content.dart, client/flutter/lib/api/stats_store.dart, client/flutter/lib/api/stats_store.g.dart, client/flutter/lib/api/updateable.dart, client/flutter/lib/api/who_service.dart, client/flutter/lib/components/content_widget.dart, client/flutter/lib/components/home_page_sections/home_page_protect_yourself.dart, client/flutter/lib/main.dart, client/flutter/lib/pages/facts_carousel_page.dart, client/flutter/lib/pages/main_pages/app_tab_router.dart, client/flutter/lib/pages/main_pages/home_page.dart, client/flutter/lib/pages/main_pages/learn_page.dart, client/flutter/lib/pages/main_pages/routes.dart, client/flutter/lib/pages/news_page.dart, client/flutter/lib/pages/onboarding/onboarding_page.dart, client/flutter/lib/pages/protect_yourself.dart, client/flutter/lib/pages/question_index.dart, client/flutter/lib/pages/symptom_checker/symptom_checker_view.dart, client/flutter/lib/pages/travel_advice.dart
* Also makes all calls to WhoService use protobufs
* Does not refactor SymptomChecker
* Need to re-add the functionality of showing a dialog if bad schema version.
Closes #1439
=> 📦🦅🧬 Refactor all content to be Provided input, instead of Stateful

client/flutter/lib/pages/about_page.dart
Perfect mean equality, Cryptographically secure, even.
This way people still know where to find themselves, while preserving the notion that order != contribution.
#883
=> Randomize A-Z or Z-A for credits; add other leads

server/appengine/src/main/java/who/RefreshCaseStatsServlet.java, server/appengine/src/main/java/who/WhoServiceImpl.java
Verified the current numbers match WHO dashboard for totals
ArcGIS service updated:
Old: COVID19_hist_cases_adm0_v5_view
New: COVID_19_Historic_cases_by_country_pt_v7_view
Fixes #1464, fixes #1413 , affects #1216
=> Fixes #1464, fixes #1413 - Make server use correct ArcGIS endpoint and support paging

client/flutter/lib/api/linking.dart, client/flutter/lib/components/home_page_sections/home_page_donate.dart, client/flutter/lib/pages/about_page.dart, client/flutter/lib/pages/onboarding/legal_landing_page.dart, client/flutter/lib/pages/question_index.dart, client/flutter/lib/pages/settings_page.dart
Help mitigate risk of having browser content in our process (where the OS version allows it, see: https://pub.dev/documentation/url_launcher/latest/url_launcher/launch.html )
=> Open urls, when possible, in system browser and remove extra blank lines in credits

NOTICE
Just symbolic link it so we don't need to update both files.
See "Symbolic link" mode here: https://github.com/WorldHealthOrganization/app/blob/a3aa8acc4b9e6150d532862f514d06f09156b6ca/NOTICE
=> SymLink NOTICE to LICENSE file (if we ever relicense to Apache)

content/credits.yaml
@jobertabma please confirm - thanks!
=> Update credits with HackerOne volunteers

client/flutter/lib/api/iso_country.dart, client/flutter/lib/api/stats_store.dart, client/flutter/lib/api/stats_store.g.dart, client/flutter/lib/components/home_page_sections/home_page_recent_numbers.dart, client/flutter/lib/components/page_scaffold/page_header.dart, client/flutter/lib/components/page_scaffold/page_scaffold.dart, client/flutter/lib/main.dart, client/flutter/lib/pages/main_pages/recent_numbers.dart, client/flutter/lib/pages/onboarding/onboarding_page.dart, client/flutter/test/api/iso_country_test.dart, server/appengine/src/main/java/who/RefreshCaseStatsServlet.java, server/appengine/src/main/java/who/WhoServiceImpl.java
Fixes #1432
The home page will fade between national and global stats.  ✨ 
Also fixed pinning the little tab bar at the top
=> Adds country stats to client and server

client/flutter/lib/api/stats_store.dart, client/flutter/lib/components/home_page_sections/home_page_information_card.dart, client/flutter/lib/components/home_page_sections/home_page_protect_yourself.dart, client/flutter/lib/components/home_page_sections/home_page_recent_numbers.dart, client/flutter/lib/pages/main_pages/home_page.dart
1. When the server fails, don't crash the UI for stats.
2. Make all home screen cards tappable.
3.
=> Various fixes!

client/flutter/lib/pages/about_page.dart
=> Debug info header

client/flutter/assets/content_bundles/symptom_poster.en.yaml
Completes work on  #1434. Still needs medical review by WHO but this is essentially a replication of their existing web page: https://www.who.int/health-topics/coronavirus#tab=tab_3
=> Symptom Poster full medical text

docs/release/manual-build.md
We use cocoapod 1.9.3 and xcode likely needs an update too.
=> Update build instructions

.github/stale.yml
- This should have human evaluation for closing issues
- Likely a periodic bug scrub
=> Don't close issues due to being stale

.github/CODEOWNERS
- Everyone added for /docs/ access
=> CODEOWNERS access: @crazybob, @yukuairoy

.gitignore, client/flutter/README.md, docs/ONBOARDING.md, server/README.md
- Build instructions for iOS
- Add \#*# to .gitignore (emacs tmp files)
=> iOS Build Guide

server/README.md, server/appengine/src/main/webapp/WEB-INF/appengine-web.xml
F4_1G => F2 instance for App Engine.
=> F2 instance for App Engine

client/flutter/pubspec.yaml
=> v0.13.0+24 version bump

.github/workflows/policy-ignored-lines.txt, client/flutter/assets/content_bundles/protect_yourself.en.yaml, client/flutter/assets/content_bundles/symptom_poster.en.yaml, client/flutter/assets/content_bundles/travel_advice.en.yaml, client/flutter/assets/content_bundles/your_questions_answered.en.yaml
Closes #1543
- "(>3 feet)" => "(3 feet)" to match who.int website
- Content updated based on WHO feedback:
- Protect Yourself
- Symptom Poster
- Travel Advice
- Your questions answered
=> Content Update based on WHO Feedback

docs/legal/apache-2.0-relicensing.txt
- Lawyer approved text
- Bruno Bowden consent
=> Apache 2.0 Relicensing

docs/legal/apache-2.0-relicensing.txt
Note: I cannot represent that this message is legally sufficient for the relicensing: I am merely recording its existence.
=> Recording relicensing message from WHO's Ayman Badr in markdownified format

docs/legal/apache-2.0-relicensing.txt
=> Apache 2.0 relicensing word wrap

client/flutter/android/app/src/main/AndroidManifest.xml, client/flutter/android/app/src/main/kotlin/org/who/WHOMyHealth/MainActivity.kt
Android Migration Following [this guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
Closes #1530
=> Android v2 embedding

.github/workflows/codeql-analysis.yml, tools/package-lock.json, tools/package.json
- lint fix codeql-analysis.yml
```
npm install
npx --no-install prettier --write '../**/*.{md,java,js,sh,yaml,yml}|*.{md,java,js,sh,yaml,yml}'
```
=> prettier => v2.1.2

server/appengine/src/main/java/who/AppStoreServlet.java, server/appengine/src/main/java/who/Client.java, server/appengine/src/main/java/who/ClientInterceptor.java, server/appengine/src/main/java/who/ForwardingServlet.java, server/appengine/src/main/java/who/NotificationsManager.java, server/appengine/src/main/java/who/RefreshCaseStatsServlet.java, server/appengine/src/main/java/who/StoredCaseStats.java, server/appengine/src/main/java/who/WhoServiceImpl.java, server/appengine/src/main/java/who/WhoServletModule.java, server/appengine/src/test/java/who/AppStoreServletTest.java, server/appengine/src/test/java/who/WhoTestSupport.java, tools/package-lock.json, tools/package.json
- Passing version of #1604
- Reformatting on Java files
```
curl -O https://patch-diff.githubusercontent.com/raw/WorldHealthOrganization/app/pull/1604.patch
git apply 1604.patch
npx --no-install prettier -w '../**/*.{md,java,js,sh,yaml,yml}|*.{md,java,js,sh,yaml,yml}'
```
=> prettier-java-plugin 0.8.0 => 0.8.3

client/flutter/lib/generated/intl/messages_en.dart, client/flutter/lib/generated/intl/messages_en_US.dart, client/flutter/lib/generated/l10n.dart, client/flutter/lib/l10n/intl_en_US.arb
=> Country selector copy updated to no longer refer to location permission

server/README.md
Documentation:
- Manually pushing static content
- Testing using curl example
Add description here
Closes #XXXX
<details>
</details>
=> Static Content Documentation

client/flutter/assets/content_bundles/protect_yourself.en.yaml
- Advice sourced from this page:
- https://www.who.int/emergencies/diseases/novel-coronavirus-2019/question-and-answers-hub/q-a-detail/q-a-on-covid-19-and-masks
- Partial fix for #1511
<details>
</details>
=> Mask guidance updated

docs/legal/apache-2.0-relicensing.txt
- For contributors who didn't do commits to the repository
- Daniel Kraft consent via WhatsApp
=> Apache 2.0 and MIT Licensing documentation

docs/legal/apache-2.0-relicensing.txt
Consent given over email for everyone listed in the commit
=> MIT and Apache 2.0 licensing

docs/legal/apache-2.0-relicensing.txt
- All consents give over email
- Add separation to avoid relicensers adding name to wrong section
=> Licensing consents

.github/workflows/policy-check.yaml, .gitignore, server/README.md, server/terraform/defaults.auto.tfvars, server/terraform/developer-guide.md, server/terraform/project.tf, server/terraform/staging.tfvars, tools/.lintstagedrc.json
Closes #1555 
How did you test the change?
=> App Engine and Firebase Terraform

client/lib/components/menu_list_tile.dart, client/lib/pages/about_page.dart, client/lib/pages/main_pages/app_tab_router.dart, client/lib/pages/onboarding/country_list_page.dart, client/lib/pages/settings_page.dart, client/test/who_settings_test.dart
Closes #1573
<details>
</details>
=> Add country selector to settings page

client/lib/components/recent_numbers_graph.dart
Add indicator on bar chart
<details>
</details>
=> Bar Graph Colors

client/assets/REPO_LICENSE, client/assets/credits.yaml
- Fixes broken credit and license in UI
- Tested codebase for any other broken symlinks:
```
find . -type l ! -exec test -e {} \; -print
```
Would be good to add automated pre-commit hooks in the future:
https://github.com/WorldHealthOrganization/app/issues/1671
<details>
</details>
=> Fix broken symlinks for credit and license

server/README.md, server/terraform/README.md
- Firebase Console
- Google Analytics
- Android app registration
- iOS app registration
- Setup temporary project through Terraform and these steps
- Verified connection between iOS and Android simulators and the Firebase instance
=> Firebase Admin Setup Docs

client/pubspec.yaml
- `flutter pub get`
- verified no change to `pubspec.lock`
- CI build
=> pubspec.yaml sorted by dependency name

docs/credits.yaml
- Sorting allows for easier deduplication and management of group
- In prep for updating credits: #883
=> Credits list sorted

client/lib/api/stats_store.dart, client/lib/api/stats_store.g.dart, client/lib/components/home_page_sections/home_page_recent_numbers.dart
Update Homepage stats to show daily cases
<details>
</details>
=> Update Homepage Stats to show daily cases

docs/TESTING.md
- Min Requirements:
- iOS 9.0 / iPhone 4S
- Android 4.4 (API 19) / Samsung Galaxy SII
- Permissions, connectivity, accessibility, installation
<details>
</details>
=> Test Plan Updates

.gitignore
=> -gitignore.* and -gitignore for files and directories

server/README.md, server/terraform/README.md
- Domain DNS setup access (google registrar)
- Server doc fixes
=> Terraform service account documentation

server/appengine/src/main/java/who/AppStoreServlet.java, server/appengine/src/main/java/who/ForwardingServlet.java, server/appengine/src/main/java/who/RefreshCaseStatsServlet.java, tools/package-lock.json, tools/package.json
- Update prettier-plugin-java to v"^1.0.1"
- Apply to existing files for several minor fixes
CI Builds
=> prettier-plugin-java => ^1.0.1

.github/dependabot.yml
=> dependabot fix label names

SECURITY.md
- VDP Plans
- Hacking server
- `--flavor hack` build setting
- Partial fix for #856
No testing beyond code review
=> SECURITY.md file

client/lib/components/page_scaffold/page_header.dart, client/lib/components/page_scaffold/page_scaffold.dart, client/lib/pages/onboarding/country_list_page.dart
=> Country selector search option #1705

server/terraform/README.md
- Production server changes must go through review first
- Other servers should go through review first as well
- Exception for emergencies
=> Privacy as Code policy

docs/TESTING.md, server/README.md
- Corrected listing of servers
- Corrected `curl` command for staging (paired with #1826)
- Testing hyperlink fixed
None. Only documentation change.
=> Server documentation fixes

client/pubspec.yaml
=> v1.0.0 - Release Candidate 1

SECURITY.md
- Link to VDP from SECURITY.md page
- Fixes #856
=> HackerOne Vulnerability Disclosure Program

.github/workflows/policy-check.yaml, server/appengine/src/main/java/who/WhoServiceImpl.java
- Limit token length to max cookie size (loose constraint)
Looked at requests and checked that are not excessive size requests
=> Sanitize FCM Token Input

.vscode/settings.json
I'm relatively confident the VSCode settings were committed by accident. They have also caused problems for me, and for other VSCode developers working on the client because they hide the client directory.
=> Remove vscode settings

.github/workflows/server.yaml
Fix based on https://github.com/google-github-actions/setup-gcloud/issues/226
Closes #1894
=> SERVER CI FIX

.github/workflows/server.yaml
Following latest usage docs:
https://github.com/google-github-actions/setup-gcloud#usage
CI server.yaml
=> google-github-actions v0.2.0

client/lib/components/recent_numbers_graph.dart
=> Last Updated Text

server/bin/run-dev-server.cmd
N/A
Ran the command on my machine.
=> Run-dev-server Windows script

client/ios/Podfile.lock, client/ios/Runner.xcodeproj/project.pbxproj, client/lib/api/user_preferences.dart, client/lib/api/who_service.dart, client/lib/main.dart, client/lib/proto/api/who/who.pb.dart, client/lib/proto/api/who/who.pbenum.dart, client/lib/proto/api/who/who.pbjson.dart, client/lib/proto/api/who/who.pbserver.dart, client/pubspec.lock, client/pubspec.yaml
=> Added Performance Monitoring + Update Protocs

client/android/app/build.gradle, client/lib/proto/api/who/who.pb.dart, client/lib/proto/api/who/who.pbjson.dart, client/lib/proto/api/who/who.pbserver.dart
=> Add Multidex

client/lib/components/page_scaffold/page_header.dart, client/lib/components/page_scaffold/page_scaffold.dart, client/lib/proto/api/who/who.pb.dart, client/lib/proto/api/who/who.pbenum.dart, client/lib/proto/api/who/who.pbjson.dart, client/lib/proto/api/who/who.pbserver.dart, docs/credits.yaml
Fixes an issue where the status bar was displaying white text on white headers making it unreadable
<details>
</details>
=> Set status bar style to be dark by default
