WorldHealthOrganization/app

.github/workflows/client.yml

Adding Mac for now cause it works.  Will need to tweak the way run scripts are coded to get it to work on Windows, but that can be done later.
Affects #81

Configures CI build for Mac

---

client/ionic/package-lock.json
client/ionic/package.json
client/ionic/prettier.config.js
client/ionic/src/App.tsx
client/ionic/src/components/ExploreContainer.tsx
client/ionic/src/pages/Tab1.tsx
client/ionic/src/pages/Tab2.tsx
client/ionic/src/pages/Triage.tsx
client/ionic/src/serviceWorker.ts
client/ionic/tslint.json

2 differences from GTS standard:
- tsconfig.json is setup as Ionic/React does, not as Google suggests
- tslint rules exempt variable names because react variable names are often components defined as functions, and default exports are the standard way of structuring react UI
Dependency added:
- gts; https://github.com/google/gts - Justification: Development only, Created by Google, NPM package appears to be owned by a Google bot
This standard will be enforced by our CI, as part of `npm test`.
In a separate CL I propose we enforce these checks as pre-commit git hooks, however that adds a few dependencies so I'd like to discuss it separately.
Closes #30
[This is also my opinion of how detailed a PR description should be]

Enforce a coding standard using gts

---

.github/workflows/client.yml

Builds iOS as part of CI. Keeps this pretty simple, uses `xcodebuild` while disabling code signing.
This is a WIP that is tough to debug locally, so pushing here. I don't have much experience with GitHub Actions so this may take a few commits to get right...
Closes #117

Configure initial CI build for iOS

---

client/ionic/src/hooks/useDynamicFlow.ts
client/ionic/src/pages/About.tsx
client/ionic/src/pages/ProtectYourself.tsx
content/credits.yaml

Closes #150.
Just a small refactor, no logic changes.

Factor out useDynamicFlow hook

---

client/ionic/package-lock.json
client/ionic/package.json

This should make it easier to make sure style is correct before people commit code.
Both dependencies added are devDependencies.
[husky](https://github.com/typicode/husky) - runs precommit hooks, widely used (18k stars), MIT license
[lint-staged](https://github.com/okonet/lint-staged) - runs a linting command (such as `gts fix`) on staged files, widely used (7k stars), MIT

Run gts fix on staged files on precommit

---

ONBOARDING.md

Adds a "npx cap update android" command to fix the issue of client/ionic/android/capacitor-cordova-android-plugins/cordova.variables.gradle not being found in Android Studio.
See https://github.com/ionic-team/capacitor/issues/1628 for a similar issue, with the suggested fix (that worked for me).
n/a
Android Studio now builds the project for me.

Added a "npx cap update android" command

---

client/ionic/src/theme/variables.css

Fonts -- use San Francisco for iOS and Roboto for Android / web.
No
I tested it on web and all text had a font set to Roboto.

Set default fonts (San Francisco and Roboto)

---

client/ionic/package.json

Remove .css files from being `gts check`'d in lint-staged. This is because by default, it appears that running `gts check` doesn't actually check any css files -- so our CI doesn't catch formatting errors in CSS files. However, it is run on precommit -- and then when you run `gts fix`, it doesn't fix the css files either. This makes for a very unpleasant development experience.
Ideally, we should eventually find out what the problem is with `gts` that makes it ignore .css files, but for now, we should just exclude .css files from being checked in `lint-staged`.

Remove .css files from being `gts check`'d in lint-staged

---

client/ionic/android/app/build.gradle
client/ionic/android/app/src/main/java/test/who/app/MainActivity.java
client/ionic/android/app/src/main/res/values/strings.xml

While the build succeeded actually running the app didn't work. There was a java class file missing.
I've recreated it by:
- Removing the android dir
- Recreating it via ionic tools
- Applying our changes (just 2 comments regarding permissions & origin)
no
By running it on my phone

Fixed android build

---

client/ionic/src/App.tsx
client/ionic/src/components/Carousel.tsx
client/ionic/src/content/flow.ts
client/ionic/src/pages/Menu.tsx
client/ionic/src/pages/WhoMythbusters.tsx
content/flows/v1/protect-yourself.ww.en.yaml
content/flows/v1/who-mythbusters.ww.en.yaml

Creates a new TextEmoji screen type that renders text at the top of the screen and a large emoji (as text) at the bottom. Creates a new WHO Myth-busters page using TextEmoji screens, and updates the Protect Yourself page to use TextEmoji screens.
I believe this solves 2 problems for us:
1. Approved, license-compatible, relevant imagery has been hard to come by. I believe we should be able to use emojis in the app without worrying about licenses, since they are rendered by the OS
2. We are attempting to build our content to match the WHO WhatsApp Bot functionality, and the bot already uses these emoji - makes it easy to transfer the content to our app
Potential concerns to investigate with using emoji:
* Will there be any cross-device rendering issues with emoji?
* Will we be losing …

feat: TextEmoji screen and WHO Myth-busters page

---

.github/pull_request_template.md

This just makes it a bit smoother to create a PR. The initial placeholder text is something that the PR creator should read through when they first see the PR -- this change will make it so that they just need to read through it, and don't need to delete it.
This is also a quite standard practice across GitHub repositories -- see, for example, React's PR template: https://raw.githubusercontent.com/facebook/react/master/.github/PULL_REQUEST_TEMPLATE.md

Comment out placeholder text in the PR template

---

client/ionic/src/pages/About.tsx

Fixes #254
The issue was that credits was initialized to {} and licenses to [], so both would evaluate as true -- so then React would try to access something like `credits.team.join(",")` and then give an error.
This PR initializes both variables to null.

Fix About page being blank

---

docs/BUILD.md

Adds BUILD docs for submitting to various app stores. #302 
**Note:** In order to prevent the app from being made available for public download, make sure to do the following on each platform:
* Apple App Store: Choose the `Release the app yourself` or `Manually release this version` option in the "Version Release" section (see [step 4 here](https://help.apple.com/app-store-connect/#/dev301cb2b3e))
* Google Play Store: Choose the `Closed` option when managing release type (see [1 in Step 1 here](https://support.google.com/googleplay/android-developer/answer/7159011))
N/A
N/A

docs: Add BUILD documentation for submitting app

---

docs/BUILD.md

Notes that Android Studio is a requirement to build.
(Actually I think it's really just the Android toolchain that comes with it)
N/A
N/A

docs: add Android Studio to dependencies in build doc

---

docs/ONBOARDING.md

Replace the invalid slack invite link with a working one. Relates to #245.
N/A
Tested by opening links in an incognito tab to verify that the invite works.

Replace invalid slack invite link

---

.github/pull_request_template.md
docs/CONTRIBUTING.md

Fixes links to other docs in the PR template and contributor guidelines.
N/A
Using the GitHub rendering of the markdown files to confirm that clicking the links goes to the right place.

docs: fix links in PR template and contributor guidelines

---

client/flutter/lib/carousel_page.dart
client/flutter/lib/page_scaffold.dart
client/flutter/pubspec.lock

This will make it so when a user taps on a slide, that it moves to the next one.
Nope
iOS simulator

Tap to move through slides

---

.github/CODEOWNERS

Require admin approval for changes to CI workflows by using GitHub's [CODEOWNERS functionality](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location).
Once this is merged, we need to check "Require Review from Code Owners."
This way, it will reduce the risk of committers extracting / leaking secrets used in CI because they cannot modify the CI workflows without admin approval (approval by @brunobowden or @SamMousa ).

Require admin approval for changes to CI workflows

---

.github/workflows/flutter-build.yml

Builds appbundle instead of apk on CI. Appbundles are better to build than apks because they are smaller and more efficient. Additionally, `flutter build appbundle` was the step we ended up taking when actually building the v0.1 app for submission to the Play Store.
(this implements part of a larger PR, #463, which isn't ready to be merged yet)
See https://flutter.dev/docs/deployment/android#when-should-i-build-app-bundles-versus-ap …

Build appbundle instead of apk on CI

---

client/flutter/lib/constants.dart
client/flutter/lib/pages/home_page.dart

Address home page text overflow on small devices.

---

client/flutter/ios/Runner.xcodeproj/project.pbxproj

The build was not working with flutter stable channel.  I followed the migration doc related to XCode 11.4 here:  https://flutter.dev/docs/development/ios-project-migration.  I'm not sure why this issue suddenly presented itself or how our CI build is working around it but I confirmed that a clean checkout on a new machine with XCode 11.3 was not working, nor was it working on my XCode 11.4 environment.  This appears to have fixed it.

This fixes the build for the flutter stable channel XCode 11.4 

---

.github/CODEOWNERS

Redo #501 in my own repo
Reflecting our new feature leads structure, closes #500
The structure:
* Pat and Ben for Client
* Shilpa for L18n - pure translations can be approved by her alone, but Client UI can also keep working independently when they need to change code and strings in one PR
* Ashwin for Release process
* Bob for Server
* General committers Bruno, Bob, Sam, Hunter, and Advay have repo-wide access
* Admins Bruno, Bob, or Sam must approve all changes to the approvers themselves or CI or CD.
Co-authored-by: Hunter Spinks <hspinks@gmail.com>

Roll-out feature-scoped commit access

---

client/flutter/lib/pages/home_page.dart

Tweak space at bottom of home screen:

Add more scroll space at bottom of home screen for iOS safe area.

---

client/flutter/lib/pages/question_index.dart

Added loading indicator to `question_index.dart`, so that while the app is loading the questions the app shows that an indicator
I chose to use a CupertinoActivityIndicator because it was naturally indeterminate and a good standard for iOS apps
No
iOS simulator

Add loading indicator to dynamic views

---

client/flutter/lib/components/list_of_items.dart

App bar height was 80 pixels taller than all other app bars.
This code updates the app bar to be the same height as the others
iOS simulator

Fix app bar height

---

.github/workflows/flutter-build.yml

Run flutter build on PRs that touch Flutter packages or any files within the `ios` or `android` directory. Changes to these files have a larger probability of breaking the build, which is not normally run on PR checks for efficiency purposes.

Run client build on pull_request

---

client/flutter/lib/components/list_of_items.dart
client/flutter/lib/components/page_header.dart
client/flutter/lib/components/page_scaffold.dart
content/credits.yaml

New PageHeader component for consistent flexibleSpace header across pages
Adds new PageHeader component.
Moved _buildHeader() and _buildBackArrow() functionality from PageScaffold component into its own component  for use across pages and components for consistent header appearance and functionality in flexibleSpace.
Header is now consistent across all current pages. Which previously was not the case.
Fixes #619
No
Tested on iOS 13.3.1 and Android 9.

Feat: add PageHeader component

---

client/flutter/lib/components/list_of_items.dart
client/flutter/lib/pages/protect_yourself.dart
client/flutter/lib/pages/question_index.dart

Fixes accessibility text scaling on all content pages. Closes #657.
Three different fixes:
1. Replace use of `RichText` with `Text.rich`
2. Set font size instead of using `textScaleFactor` (`textScaleFactor` shouldn't be used just to change font size)
3. Manually changed base font size of HTML items to use device's `textScaleFactor`
No.
Manually on iOS by changing font size.
Before:
After:

fix: accessibilty scaling of font sizes on content pages (#657)

---

client/flutter/lib/pages/onboarding/notifications_page.dart

This PR makes it so if they decide not to enable notifications(skip) then their onboarding will close without showing the location request
No
iOS simulator

close on notifications skip

---

client/flutter/assets/content_bundles/mythbusters.en.yaml
client/flutter/lib/api/question_data.dart

Points the Mythbusters screen to the Mythbusters content
N/A

[content] Use Mythbusters content on Mythbusters screen

---

client/flutter/lib/pages/settings_page.dart
content/credits.yaml

Do no use SelectableText for the settings page
For some reason `SelectableText` widget was used on the Settings page, making text selectable on a long-press. But the pop-up doesn't show any actions/icons to do and also there's no reason for the text to be selectable (I did not find any other screen in the app where it is).
=> Used default `Text` instead
Issue:
No.
Tested on Google Pixel 2.

Do no use SelectableText for the settings page

---

client/flutter/lib/pages/home_page.dart
client/flutter/lib/pages/onboarding/legal_landing_page.dart
client/flutter/lib/pages/onboarding/location_sharing_page.dart
client/flutter/lib/pages/onboarding/notifications_page.dart
client/flutter/lib/pages/onboarding/onboarding_page.dart

Correct back button behavior during onboarding.
The hardware back button (e.g. Android's back button) was **NOT** handled during onboarding. This causes several issues:
- When pressing back the Onboarding would be popped, showing the home page of the app
- At this moment analytics is enabled, while the user didn't press Get Started
- Also onboarding would be marked as completed, so not popping up again next time, while it wasn't.
**=> We're missing the opportunity to ask for notifications and location!**
To fix it I use the `WillPopScope` widget which catches the back button and let's you handle/veto it.
With these fixes in place, the current behavior of the app is:
No.
Tested on:
**Please test on a real iPhone before merging!**
**GIFs:** (click for larger)
| Bad behavior before 1 | Bad …

Correct back button behavior during onboarding

---

client/flutter/ios/Runner/Info.plist

This enables localization on iOS by adding the list of supported language codes to the Runner info.plist file.  I believe that only the language codes is required and not the language_country combinations.

Add our list of supported languages to the Runner info.plist.

---

client/flutter/lib/components/page_scaffold/page_header.dart

Unpins the header
No
iOS simulator

Unpin header for v2

---

.github/workflows/flutter-build.yml
.github/workflows/flutter-test.yml

Use the lowest permitted compatible Flutter repo instead of whatever is supposedly "stable"
Fixes this:
```
The current Flutter SDK version is 0.0.0-unknown.
Because flutter_svg 0.17.3+1 requires Flutter SDK version >=1.6.7 <2.0.0 and no versions of flutter_svg match >0.17.3+1 <0.18.0, flutter_svg ^0.17.3+1 is forbidden.
So, because WHOFlutter depends on flutter_svg ^0.17.3+1, version solving failed.
pub get failed (1; So, because WHOFlutter depends on flutter_svg ^0.17.3+1, version solving failed.)
##[error]Process completed with exit code 1.
```

[build break] Pin CI flutter to v1.12.13+hotfix.5

---

client/flutter/lib/main.dart

Set app bar brightness to light
Sets status bar dark by default. Fixes [#763](https://github.com/WorldHealthOrganization/app/issues/763), 
No
Tried on Android and iOS simulators, both light and dark mode and real iOS devices

P1 - Set status bar color black by default

---

client/flutter/ios/Runner/Info.plist

Update info plist to fix app push notification permissions
Fixes error,
```
Missing Info.plist value. The Info.plist key 'BGTaskSchedulerPermittedIdentifiers' must contain a list of identifiers used to submit and handle tasks when 'UIBackgroundModes' has a value of 'processing'. For more information, refer to the Information Property List Key Reference at https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html.
```
See https://github.com/FirebaseExtended/flutterfire/issues/1694 for the fix

update info plist to fix push notification permissions

---

client/flutter/ios/Runner/Info.plist

Otherwise, we get an error, "The bundle uses a bundle name or display name that is already taken."

Change CFBundleDisplayName to WHO COVID-19

---

client/flutter/ios/Runner/AppDelegate.swift

Fixes https://github.com/WorldHealthOrganization/app/issues/776 by setting the locale as soon as the app launches. There is a bug currently in Flutter that will be fixed by https://github.com/flutter/engine/pull/17473, but that will take some time to roll through dev/beta/stable.  In the mean time, this fix is safe and will cooperate fine even once the issue is fixed upstream.  Once https://github.com/flutter/engine/pull/17473 has …

Fix late locale initialization on iOS

---

server/appengine/src/main/webapp/WEB-INF/web.xml

Emojis were not being interpreted correctly because the Content-Type header field was not set correctly. [App engine docs](https://cloud.google.com/appengine/docs/standard/java/config/appref#mime_types_for_static_files) explain this behavior. I have fixed this issue using their recommended method.
I associated a custom MIME type for yaml extension static files using <mime-mapping> elements in web.xml. The mime-type I am using is …

[p0][server] Yaml static file mime-types (#844)

---

client/flutter/ios/Runner/Info.plist

Adding in these changes that were added to the v0.4.1 release branch so they're on master:
- Update info plist to fix push notification permissions (#834)
- Change CFBundleDisplayName to WHO COVID-19 (#835)

Update Info.plist with changes in v0.4.1 release

---

client/flutter/lib/components/page_scaffold/page_header.dart
client/flutter/pubspec.lock
client/flutter/pubspec.yaml

Uses the `auto_text_size` package to automatically size the text in the header title and subtitle.
Closes #651 
* [`auto_text_size`](https://pub.dev/packages/auto_size_text): **not** from a verified dev, but has >200 likes on pub.dev, and @advayDev1 did a cursory review of v2.1.0 for security
<details>
<summary>iPhone 8 screenshots</summary>
</details>

[feat] Use auto text size for header text to fix overflow

---

client/flutter/lib/components/news_feed_item.dart

Closes https://github.com/WorldHealthOrganization/app/issues/920
No
Increasing the text size until it overflowed.

fix: allow news feed subheadings to use multiple lines

---

client/flutter/ios/Podfile.lock
client/flutter/lib/api/content_loading.dart
client/flutter/pubspec.lock
client/flutter/pubspec.yaml

This PR adds client side caching of the yaml files using the `flutter_cache_manager` package.  Cache expiration is controlled by the server cache control max-age response header (currently 10 minutes).  
I tested this by logging when the files were downloaded vs returned from the cache.  I also did a negative test by breaking the URL in order to see that the fallback behavior was still applied.
This PR adds two package: `https://pub.dev/packages/flutter_cache_manager` and  `https://pub.dev/packages/path_provider`.  The `path_provider` was already a (transitive) dependency of our project and is not new.

Client-side caching of server content

---

api/who/who.proto
server/appengine/src/main/java/who/RefreshCaseStatsServlet.java
server/appengine/src/main/java/who/StoredCaseStats.java
server/appengine/src/main/java/who/WhoServiceImpl.java
server/appengine/src/main/java/who/WhoServletModule.java
server/appengine/src/main/webapp/WEB-INF/cron.yaml

Every 5 minutes refresh case stats from new WHO pipeline (0.003 RPS load)
Closes #928
Not sure if this is where cron.yaml is supposed to live in Java standard AE... @crazybob and do we have to deploy it separately from the WAR?
Test:
```
$ curl -i  -H 'X-Appengine-Cron: true' -X GET     http://localhost:8080/internal/cron/refreshCaseStats
HTTP/1.1 200 OK
Server: Development/1.0
Date: Tue, 07 Apr 2020 23:46:04 GMT
Cache-Control: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Content-Length: 0
$ curl -i     -H 'Content-Type: application/json' -H 'Who-Client-ID: 00000000-0000-0000-0000-000000000000' -H 'Who-Platform: IOS' -X POST -d ''     http://localhost:8080/WhoService/getCaseStats
HTTP/1.1 200 OK
Content-Type: application/json
Server: Development/1.0
Date: Tue, 07 Apr 2020 23:46:10 …
```

[feat] Cron for pipeline stats from WHO

---

client/flutter/lib/pages/onboarding/permission_request_page.dart

- Closes https://github.com/WorldHealthOrganization/app/issues/940
- Increases the contrast ratio of the skip button on the onboarding page from 1.59:1 to 4.5:1
#C9CDD6 to #6E7691
No
Running on my Android device
Before:
After:

fix: increase contrast of onboarding skip button

---

client/flutter/android/app/src/main/AndroidManifest.xml
client/flutter/android/app/src/main/kotlin/org/who/WHOMyHealth/MainActivity.kt

- Closes https://github.com/WorldHealthOrganization/app/issues/935
- Reverts to the old flutter embedding system(I believe) which doesn't have this issue. I'm not aware of any drawbacks to this.
No
No green outline was being shown previously, now it works as expected.

Component borders weren't being shown via TalkBack on Android.

---

client/flutter/lib/components/arrow_button.dart
content/credits.yaml

Fixes #979 - font size overflowing on buttons (see screenshots below)
No.
Manually on iOS simulator
Before
After
Before
After

Fix: arrow button overflowing (fixes #979)

---

client/flutter/lib/components/latest_numbers_graph.dart
client/flutter/lib/pages/latest_numbers.dart

Responds to design feedback and removes a TODO to use the `epochMsec` in the API response. Uses cumulative totals to build the graph instead of daily figures, removes the smoothing on the graph, and creates the points in the line graph based on the snapshot timestamp instead of assuming that there is exactly 1 snapshot per 24 hour period.
N/A
<details>
<summary>Screenshot</summary>
</details>

[feat] Update Latest Numbers graph

---

api/who/who.proto
client/flutter/android/app/src/main/AndroidManifest.xml
client/flutter/ios/Podfile.lock
client/flutter/lib/api/who_service.dart
client/flutter/lib/pages/onboarding/location_sharing_page.dart
client/flutter/pubspec.lock
client/flutter/pubspec.yaml
server/appengine/src/main/java/who/Client.java
server/appengine/src/main/java/who/WhoServiceImpl.java

- Removes all geocoding and its dependencies
- Switches Android permissions to coarse location, and asks at runtime for Low accuracy iOS location
- Quantizes location to S2CellId at L9 (strictly greater than 100km^2)
- Removes all other fields of location communication
- Server-side validation of s2 token being of a coarse-enough level to avoid pollution and for privacy
- New dependency: Have reviewed the specific pinned version from pub.dev.
TESTED=true with iOS and Android simulator against Dev app engine backend
Close #1040

Client/server: Communicate location solely using S2 cell ids at L9

---

client/flutter/lib/components/swipeable_open_container.dart
content/credits.yaml

Makes the transition from home page to subpages much nicer.
When swiping back from iOS everything now lines up.
It also removes me from being in the credits twice :-)
Closes #993 
No
Manually

Fix: make animation from home page smoother (closes #993)

---

client/flutter/assets/content_bundles/protect_yourself.en.yaml
client/flutter/lib/pages/protect_yourself.dart

This PR changes the "Protect Yourself" page to use HTML for the dynamic content instead of the ad-hoc markdown syntax.  
I believe it looks identical with the exception that one line is breaking slightly differently.
Closes #1030

Change "Protect Yourself" page to use HTML for dynamic content.

---

client/flutter/lib/components/loading_indicator.dart
client/flutter/lib/pages/protect_yourself.dart
client/flutter/lib/pages/question_index.dart
client/flutter/lib/pages/travel_advice.dart

This PR adds a loading indicator to the protect yourself pages and refactors the widget so that it is used in the same way across pages.

Add loading indicator to "Protect Yourself" page and refactor widget.

---

client/flutter/assets/content_bundles/home_index.en.yaml
client/flutter/lib/api/content/schema/index_content.dart
client/flutter/lib/api/linking.dart
client/flutter/lib/components/home_page_sections/home_page_header.dart
client/flutter/lib/components/home_page_sections/home_page_information_card.dart
client/flutter/lib/components/home_page_sections/home_page_protect_yourself.dart
client/flutter/lib/pages/main_pages/app_tab_router.dart
client/flutter/lib/pages/main_pages/home_page.dart

Drives home page content from an index content bundle. Allows the server to specify which widgets are on the home page, and in what order. Currently supported index item types are: `recent_numbers`, `protect_yourself`, and `information_card`. Information cards support linking to external URLs. The home header / promo content can also be specified in the content bundle.
One thing to note is that because `IndexItem` objects now support essentially empty content with just a `itemType` specified, we lose the safety of requiring certain fields to be set (see [diff](https://github.com/WorldHealthOrganization/app/pull/1169/files#diff-c95da6beb14f1aeb66ae726d3a2b8a8aR100-R102)).
Open TODOs that I might address in this PR:
Closes #1165 
Closes #1174 
Closes #1175 
---

[feat] Home index content bundle

---

client/flutter/lib/components/home_page_sections/home_page_donate.dart
client/flutter/lib/components/home_page_sections/home_page_header.dart

The headers should never rebuild as their clippers never change

Bug Fix: Clippers should not re-clip

---

client/flutter/lib/main.dart
client/flutter/lib/pages/main_pages/routes.dart
client/flutter/lib/pages/onboarding/onboarding_page.dart

Add the Issue number(s) assigned to you that this PR fully resolves, if any
Closes https://github.com/WorldHealthOrganization/app/issues/1205
The router was pushing two routes, `/` and `onboarding`. You can actually start on the onboarding page, hit the back button, and find yourself on the home page as `/` is the name of the home page route.
I renamed the `/` route to `/home` which fixes the issue, by not having a `/` route it's unlikely that this issue will pop up again but Flutter requires either `builder`, `home`, `onGenerateRoute` or `onUnknownRoute` to be specified as a result otherwise it apparently has no fallback when routing fails.
On a side note, it'd be nice if we define route names as static strings inside each page e.g.
```
class OnboardingPage extends StatefulWidget { …
```

fix: prevent premature home page initialisation  

---

.gitignore
server/appengine/src/main/java/who/RefreshCaseStatsServlet.java

Switch daily case stats from WHO's Sprinklr dashboard pipeline to WHO's ARCGIS pipeline.
Closes #1093 
N/A
NO
From 'app/server' directory (2 terminals)
Terminal 1
git checkout master;
gradle clean && gradle build;
./bin/run-dev-server.sh;
Terminal 2
TMP_OUTPUT_DIR=~/Desktop/tmp/who-output/master;
mkdir -p $TMP_OUTPUT_DIR;
curl -XPOST http://localhost:8080/WhoService/getCaseStats -d '' -H "Content-Type: application/json" -H "Who-Client-ID:a67eda24-90c3-11ea-bb37-0242ac130002" -H "Who-Platform: WEB" | jq '.' > $TMP_OUTPUT_DIR/output-after-clean-build-getstats-before-cron.json
curl -i -H 'X-Appengine-Cron: true' -X GET http://localhost:8080/internal/cron/refreshCaseStats > $TMP_OUTPUT_DIR/output-internal-cron.txt;
curl -XPOST http://localhost:8080/WhoService/getCaseStats -d '' -H …

refactor(case-stats): Daily case stats come from WHO ARCGIS endpoint

---

client/flutter/lib/components/carousel/carousel.dart

Closes https://github.com/WorldHealthOrganization/app/issues/1247
uses `_animatedVisibility` to hide the next/previous arrow buttons when on the first/last page respectively while still occupying the size of the buttons automatically. It's similar to the `Visibility` widget but with a 200ms fade animation.
<details>
First page:
Second page:
Last page:
</details>
---

fix: hide next/prev carousel buttons

---

client/flutter/lib/components/menu_list_tile.dart
client/flutter/lib/pages/about_page.dart
client/flutter/lib/pages/settings_page.dart

- Closes https://github.com/WorldHealthOrganization/app/issues/1250
- Moves the `menuItem` component out of the settings page and into the components folder(renamed to `MenuListTile`).
- Replaces the `LinkTextSpan`s with vertically stacked `MenuListTile`s
<details>
Before:
After:
</details>
---

refactor: use MenuListTile in AboutPage

---

client/flutter/lib/pages/onboarding/country_select_page.dart

I don't think the `CupertinoPageScaffold ` is needed here. A small side effect of using a `MaterialApp` is that a few widgets like `Text` need to be wrapped in `Material` or the effect in the screenshot occurs. This is done automatically when using a Material `Scaffold` widget.
<details>
Before:
After:
</details>
---

replace CupertinoPageScaffold with Material in CountrySelectPage

---

client/flutter/lib/api/content/content_loading.dart

Currently, this falls back to the locale country. Since all users should be forced to select a country when onboarding, that shouldn't be relevant unless the user's preferences are blown away. However, this will help for the phones that already have the app and will not go through onboarding again.
Note that to guarantee that the user gets the correct country-specific content, we will need to have a YAML file for each language-country combination.
Closes #1217 
---

[feat] Use user-selected country for content bundles

---

client/flutter/lib/pages/onboarding/legal_landing_page.dart
client/flutter/lib/pages/onboarding/permission_request_page.dart

Fixes #1307 -- change text color and background color of "Get Started" and "Allow Notifications" buttons to match the mockup.
<details>
</details>

Fix onboarding screen button color regressions

---

client/flutter/lib/components/home_page_sections/home_page_information_card.dart
client/flutter/lib/pages/main_pages/home_page.dart

Awaiting finalized asset to be included, but should be able to add `image_name: <svg-name>` to the `home_index.en.yaml` when ready to include.
Closes #1245 
<details>
<summary>With Placeholder SVG</summary>
</details>
---

[feat] Add optional image to HomePageInformationCard

---

client/flutter/lib/components/button.dart
client/flutter/lib/components/home_page_sections/home_page_donate.dart
client/flutter/lib/components/home_page_sections/home_page_header.dart
client/flutter/lib/components/home_page_sections/home_page_information_card.dart
client/flutter/lib/components/learn_page_promo.dart
client/flutter/lib/pages/onboarding/permission_request_page.dart

Leaves the buttons that do not have rounded rect backgrounds, specifically the home page section "Learn more >" buttons, the carousel next/prev buttons, and the check up page intro terms link
Closes #1219 (at least enough to open specific issues for specific elements that need debouncing)
Closes #1156 (at least enough to open specific issues for specific elements that need splash)
---

[refactor] Use new Button component for all rounded rect buttons

---

api/who/who.proto
server/README.md
server/appengine/build.gradle
server/appengine/src/main/java/who/Client.java
server/appengine/src/main/java/who/Environment.java
server/appengine/src/main/java/who/FirebaseModule.java
server/appengine/src/main/java/who/NotificationsManager.java
server/appengine/src/main/java/who/Topics.java
server/appengine/src/main/java/who/WhoServiceImpl.java
server/appengine/src/main/java/who/WhoServletModule.java
server/appengine/src/test/java/who/TopicsTest.java
server/build.gradle

Closes #1221, closes #1000
Client already sends isoCountryCode, this saves it.
It will also register the client for topics `ALL~LOCATION` (global) and `ALL~LOCATION~isoCountryCode` (per country) topics.
In the future we could have `TESTINGCENTERS~LOCATION~isoCountryCode` etc. if users only want a few types of notifications.
[redacted] GCP traces:
```
2: {
time: "2020-05-14T01:53:50.355Z"
severity: "INFO"
logMessage: "who.NotificationsManager updateSubscriptions: SUCCESS - Subscribed d0zOdIG6[redacted]KusQJXig2uNK8gSFgxBD1hjmBGE4XyQQQvzbOVP to topic ALL~LOCATION
"
sourceLocation: {3}
}
3: {
time: "2020-05-14T01:53:50.660Z"
severity: "INFO"
logMessage: "who.NotificationsManager updateSubscriptions: SUCCESS - Subscribed d0zOdIG[redacted]KusQJXig2uNK8gSFgxBD1hjmBGE4XyQQQvzbOVP to topic …
```

🎶🦜 Server country and push notification topic registration

---

client/flutter/assets/content_bundles/get_the_facts.en.yaml

For consistency with the other titles on the page.

Add a period after "Pneumonia vaccines..."

---

docs/release/README.md
docs/release/manual-build.md
docs/release/prepare-release.md

Update release documentation with the latest processes we have been using. I've updated:
- the QA testing process
- the process of preparing a release for the WHO to use
- the WHO's process of pulling a release and building it
@hspinks let me know if I covered all the steps you've been taking in prepare-release.md.

Update release documentation for processes on QA testing, preparing a release

---

client/flutter/lib/api/user_preferences.dart
client/flutter/lib/main.dart
client/flutter/lib/pages/onboarding/onboarding_page.dart

Closes #1302
Keeps the user's preference for disabling analytics if they previously opted out (tested locally). Note this will still show the user the notification permission request screen even if they have already turned it on or rejected the native dialog.
---

Re-TOS & re-onboard all users

---

client/flutter/lib/api/content/content_loading.dart
client/flutter/lib/api/content/content_store.dart
client/flutter/lib/api/display_conditions.dart
client/flutter/lib/api/user_preferences.dart
client/flutter/lib/api/user_preferences_store.dart
client/flutter/lib/api/user_preferences_store.g.dart
client/flutter/lib/main.dart
client/flutter/lib/pages/main_pages/routes.dart
client/flutter/lib/pages/onboarding/onboarding_page.dart
client/flutter/lib/pages/symptom_checker/symptom_checker_view.dart
client/flutter/pubspec.lock
client/flutter/pubspec.yaml

By default we will use locale-country, but once a user selects a country,
we will actually use that country in the content YAML loading.
This starts the proper refactor of UserPreferences into a Store to use
it as an observable dependency.
Dependency: observer_producer - a verified dep I open-sourced from work
Fixes #1290, Fixes #1467
TESTED=Look at the logs as you change the country showing which YAML files are loaded.

Fixes #1290, Fixes #1467: Load country specific-content, and fix country list bug

---

client/flutter/assets/content_bundles/home_index.en.yaml
client/flutter/ios/.gitignore
client/flutter/ios/Podfile.lock
client/flutter/lib/api/content/caching.dart
client/flutter/lib/api/content/content_loading.dart
client/flutter/lib/api/content/content_store.dart
client/flutter/lib/api/updateable.dart
client/flutter/lib/api/user_preferences.dart
client/flutter/pubspec.lock
client/flutter/pubspec.yaml

- Home promo per David's mocks
- Refactor the content updating to be parallel async
- Don't wait for timeout when there is no network connectivity
- Refresh content on connectivity change
- When there is a network version and a binary asset version, choose the newer content
- Let the underlying cache store data for many years, so we can still return old cached content if it is newer than the binary asset content
- Actually return new network versions
- Adds `connectivity` dep (which is run by flutter.dev, which depends on Reachability pod)
Fixes #1490 ; Fixes #1452 ; Fixes #1429
TESTED = Locally on my Android phone with various combos of network connectivity and varying versions of the home content I was modifying.

🏡 New home promo ; 🆕 use newer content ; and more fixes

---

docs/devdesign/System-Architecture-Diagram.csv
docs/devdesign/architecture.md

Note that this diagram reflects what the production system would look like.  The production Google Cloud accounts would need to actually be configured for example for data location, security, and privacy, etc.  The committed CSV is exported from Lucidchart.
The PDF and VDX are archived here for posterity: note the license exceptions therein.
[WHO COVID-19 System - v0.5.pdf](https://github.com/WorldHealthOrganization/app/files/5252636/WHO.COVID-19.System.-.v0.5.pdf)
[WHO COVID-19 System - v0.5.vdx.zip](https://github.com/WorldHealthOrganization/app/files/5252641/WHO.COVID-19.System.-.v0.5.vdx.zip)
Co-authored-by: Hunter Spinks <hspinks@gmail.com>

Commit architecture diagram

---

docs/devdesign/System-Architecture-Diagram.csv

Main correction is that client build depends on dependencies not only from pub.dev.
(See exceptions to MIT license inside these attachments, which are not being committed to repo)
[WHO COVID-19 System - v0.6.pdf](https://github.com/WorldHealthOrganization/app/files/5269938/WHO.COVID-19.System.-.v0.6.pdf)
[WHO COVID-19 System - v0.6.vdx.zip](https://github.com/WorldHealthOrganization/app/files/5269941/WHO.COVID-19.System.-.v0.6.vdx.zip)

Arch Diagram updated to v0.6

---

.github/workflows/client.yaml
client/flutter/ios/Podfile.lock
client/flutter/lib/api/notifications.dart
client/flutter/lib/pages/main_pages/app_tab_router.dart
client/flutter/pubspec.lock
client/flutter/pubspec.yaml

Run `flutter upgrade` to continue development
Closes #1576 
Flutter release notes (v1.22.0 and v1.22.1 hot fix):
- https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-1.22.0
- https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#1221-october-8-2020
Major Changes:
- Local and CI build environments updated
- Provisional notifications case for iOS
https://robopress.robotsandpencils.com/provisional-notifications-on-ios-17dac1fd502e
`flutter pub upgrade` special changes:
- nullsafety prerelease libs (stable quality)
flutter/flutter#67473 (comment)
- Pinned libraries that need to be updated later:
- "share": v0.6.3+6 due to build warning treated as error in 0.6.5+2
- "flutter_cache_manager": v1.1.3 due to breaking API change in 1.4.0

Flutter => 1.22.1

---

.github/pull_request_template.md
server/appengine/src/main/java/who/Environment.java

- App Engine to identify WHO production project in GCP (see #1298)
- Remove "summary" from PR Template as commit message should suffice
<details>
</details>

WHO Prod Project

---

client/flutter/lib/pages/about_page.dart

- Debug info is always show at the bottom of "About the App"
- Copy button can be used to make a copy
- Might be nice to copy also if debug info text is tapped

Debug Info always shown and copyable

---

client/lib/components/recent_numbers_graph.dart

Makes the tooltip for case count show the date rather than the case amount
Add the Issue number(s) assigned to you that this PR fully resolves, if any
Closes #1575 #1460
<details>
</details>
---

Date for case count tooltip

---

docs/legal/apache-2.0-relicensing.txt

To be clear, you still need to get the consents of everyone else.
The commit contains the following legend:
This limited consent is based on the following:
* The consent by Ayman Badr on behalf of the World Health Organization to accept, and to license WHO's own contributions under, that certain form of license at https://raw.githubusercontent.com/WorldHealthOrganization/app/4d1a611bfa5ea807a8c3d2551beecfe8bc7f8cb2/LICENSE which includes a WHO copyright statement and also documents other components not licensed under the expected-new main Apache License 2.0 (which is documented in email from Ayman). Because the specific PR that Ayman referenced has been superseded, the file has been archived at https://web.archive.org/web/20200916041246/https://raw.githubusercontent.com/WorldHealthOrganiza …

Advay Mengle limited consent to Apache 2.0 relicensing

---

client/lib/components/carousel/carousel_slide.dart

AutoScale title on Get the Facts pages
Closes #1240
- This will not scale up the text on big screens
- The minimum size of the text will be half of the original rate on small screens
- The scaling down is linear based on screen width
- Screens above 550 pixels wide see no changes
- Screens below 275 pixels are shown text one half the size of the regular size
- Screens inbetween see a size equal to their size, divided by 550, multiplied by the normal size
<details>
As I understand that autoscaling can be worrying I have tested on many devices -- including devices that this change does not affect the size of the text of.
**iPhones**
- iPhone SE
- iPhone 8
- iPhone 8+
- iPhone 11
**Androids**
- Galaxy Nexus
- Nexus 4
-  Pixel 3
- Pixel 3 XL
- Pixel 3a
- Pixel …

Learn More Page AutoScale text

---

client/lib/components/learn_page_promo.dart

Added blurred text behind the subtitle text
Related to suggestion in #1511
Closes #1571 
<details>
</details>

Learn More Headline Opaque Shadow

---

client/lib/components/recent_numbers_graph.dart

Fix Loading on stats page charts
<details>
First two screenshots show charts once loaded functioning properly, third shows loading functioning properly
</details>

Fix Loading on Stats Page Charts

---

LICENSE

For ease of the upcoming attempted relicense I've relicensed my underlying repository linked here to Apache 2.
The only people who seem to have worked on the files I pulled over into this repo seem to be @brunobowden and @hspinks .  If you both agree to this relicense by saying "I agree" I will remove the VOID and Bruno can submit.
As always this is not legal advice and I cannot represent that this is legally sufficient to perform the relicense.
Please note that if you don't submit this now, it is possible others (other than Hunter and Bruno) will further adapt my sandbox-licensed work and you may need more agreements here.

Propagate relicense of madvay/actions-sandbox

---

client/lib/pages/main_pages/recent_numbers.dart

- Changed the default Aggregation emun to be the value of the daily cases
- Changed the order of the daily and total values so it loops through the daily first, intern switching the default stat.
<details>
</details>

Made daily default on stats page

---

client/lib/main.dart

No privacy alert made shorter for dev builds

---

client/README.md
client/lib/main.dart
docs/release/manual-build.md

Update release build instructions
- Versions update
- Remove `$(git rev-parse --show-toplevel)` from cd commands for greater clarity
- Shorten dev build warning

No privacy alert + Release versions

---

client/android/app/build.gradle
client/android/build.gradle

- Fabric repo and dependencies removed
- Moved crashlytics plugin above android config to match documentation
https://firebase.flutter.dev/docs/crashlytics/overview#3-platform-integration
- Firebase Analytics classpath removed as not mentioned in documentation:
https://firebase.flutter.dev/docs/analytics/overview#installation

Fabric cleanup - remnants from transition to Firebase Crashlytics

---

docs/legal/apache-2.0-relicensing.txt

Partial fix for #1546
- Git record of consents given over email and on GitHub
- Verified as excluding @advayDev1, @amourakora and @Moosphan

Relicensing consents from GitHub and email recorded in git repo

---

client/ios/Flutter/AppFrameworkInfo.plist

- Based on this comment:
https://flutter.dev/docs/deployment/ios#updating-the-apps-deployment-version
Error:
```
ERROR ITMS-90208: "Invalid Bundle. The bundle Runner.app/Frameworks/App.framework
does not support the minimum OS Version specified in the Info.plist."
```
Tested on CI and with new deployment
<details>
</details>

iTune invalid bundle fix

---

.gitignore
tools/.lintstagedrc.json
tools/terraform-fmt-validate.sh
tools/verify-client.sh
tools/verify-server.sh

- terraform fmt -recursive
- terraform validate   (no recursive option)
- tested with many local using pre-commit checks
- ignore files matching `*-ignore.*`

Terraform fmt and validate pre-commit checks fixed

---

docs/credits.yaml
docs/legal/apache-2.0-relicensing.txt

- Chris Juneja consent for Apache 2.0 relicensing
- Tabassum Wajid added to credits

Chris Juneja relicensing consent + Tabassum Wajid added to Credits

---

.github/policy-ignored-lines.txt
LICENSE

Based on consent of contributors as recorded in:
[docs/legal/apache-2.0-relicensing.txt](https://github.com/WorldHealthOrganization/app/blob/master/docs/legal/apache-2.0-relicensing.txt)
The GitHub consents are publicly posted here:
#1645
Notes:
- Correction to commit 8a96d8f. @Moosphan gave consent over email but
commit message incorrectly states he should be excluded.
- Only GitHub consent not received was @amourakora for commit 91b2c88,
this removed a single apostrophe and is considered trivial.
- Two non-GitHub consent sought and not received:
- Stephen Walters: He created the "WHOapp v0.1 Analytics and
Instrumentation" doc that is under his personal account and not hosted
on the shared Google Drive. Considered immaterial for relicensing. …

MIT License to Apache 2.0 License

---

client/lib/api/alerts.dart
client/lib/api/content/content_store.dart
client/lib/api/content/last_update.dart
client/lib/api/user_preferences.dart
client/lib/components/page_scaffold/page_scaffold.dart
client/pubspec.lock
client/pubspec.yaml

Added UI indicating if a cache could be outdated
<details>
</details>

Stale Content Warning

---

.github/workflows/client.yaml

1. `flutter build appbundle`
2. `flutter build apk`
This duplicative as the apks should be generated from the appbundle
using bundletool. That will be done later.
Fixes #1725 
CI build

CI appbundle build

---

client/lib/proto/api/who/who.pbenum.dart

Fix CI by regenerating protobuf files. See failing check at https://github.com/WorldHealthOrganization/app/pull/1736/checks?check_run_id=1396513114

Fix CI by regenerating protobuf files

---

client/lib/main.dart
server/terraform/README.md
server/terraform/hack/main.tf
server/terraform/modules/myhealth/main.tf
server/terraform/modules/myhealth/variables.tf
server/terraform/prod-in-dev/main.tf
server/terraform/prod/main.tf

- Optional creation of project in Terraform
- Production uses existing project with access limited to that project
- "prod-in-dev" to replicate limited permissions for development
- Fixes to allow seamless project creation without errors:
- depends_on dependencies fixed
- Enabled cloudresourcemanager and appengine APIs
Documentation:
- Extensive documentation of project creation and service accounts
- Policy for keeping server config and code/docs in sync to support:
- Transparency on configuration
- Privacy policy compliance
Partial fix for #1298
Terraform apply for "prod-in-dev" and also "prod"

Production Terraform

---

server/terraform/hack/main.tf
server/terraform/modules/http-load-balancer/main.tf

- TLS 1.2 Minimum
- Compatible with Android 4.4 (minimum) and iOS 6 (iOS 9 is minimum)
- https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2&key=62
- https://www.ssllabs.com/ssltest/viewClient.html?name=Safari&version=9&platform=iOS%209&key=114
- "MODERN" profile for balance between compatibility and security
- Terraform implementation
Partial fix #649 
SSL Labs confirmed TLS 1.2 and above only. TLS 1.1 and below disabled.
https://www.ssllabs.com/ssltest/analyze.html?d=hack.whocoronavirus.org&latest

TLS 1.2 SSL Policy

---

client/lib/api/user_preferences.dart

Properly set firebase auto init option when notifications / analytics settings are changed. Fixes #1308
`firebaseMessaging.setAutoInitEnabled(false)` is called whenever both notifications and analytics are turned off. Otherwise, when either of them are turned on, `firebaseMessaging.setAutoInitEnabled(true)` is called.
Logged to the console whenever `setAutoInitEnabled` was called and then manually tested on the iOS simulator to ensure it is called correctly in various scenarios.

Properly set firebase auto init option when notifications / analytics settings are changed

---

.github/workflows/client.yaml

Fix build:
```
before:
- run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
after
- run: echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH
```
Documentation and Vulnerability:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w
CI build

add-path GitHub Actions fix

---

server/terraform/modules/http-load-balancer/main.tf
server/terraform/modules/myhealth/main.tf

- Pinned hashicorp providers: external, null, random
- prevent_destroy for critical resources:
- project, app_engine, firebase, static IPv4 address
`terraform apply` on who-mh-dev project

Terraform: pin dependencies and protect resources

---

server/terraform/modules/myhealth/main.tf
server/terraform/staging/main.tf

who-mh-staging as new project. Fixes #1702 
Logging `depends_on` for robust bucket creation
- Bucket creation initially fails as project doesn't exist:
- `Error: Error creating Bucket: googleapi: Error 404: Project does not exist: who-mh-staging`
- Then Terraforms believes that bucket exists but fails trying to find it:
- `Error: googleapi: Error 404: Bucket europe-west1-logs-bucket does not exist`
- Workaround was to delete the resource in terraform.tfstate then recreate it
- This fix will ensure that none of these errors happen in the first place
`terraform apply`

who-mh-staging + robust bucket creation

---

server/bin/deploy-server.sh

- App Engine ingress set to `internal-and-cloud-load-balancing`
- Disables who-mh-hack.appspot.com domain
- Partial fix for #649
```
server/bin/deploy-server.sh who-mh-hack
```

Require Load Balancer for all App Engine traffic

---

server/terraform/modules/http-load-balancer/main.tf
server/terraform/prod/main.tf

- covid19app.who.int domain added to Prod terraform
- Randomize ssl-cert name as it can't update in place
- Partial fix for #1298 
`terraform apply` for both staging and then prod

covid19app.who.int production domain

---

.github/CODEOWNERS

- Full access across repo
- Matthew and Bruno worked together for many years at Google
- Matthew replacing @yukuairoy for sensitive GitHub workflows
Tested post merge but fairly straight forward.

@matthewblain added to CODEOWNERS

---

server/terraform/modules/myhealth/main.tf

Create a placeholder Google Cloud Armor security policy blocking IP addresses.
Uses a loopback placeholder with a CIDR and IP example.
To edit interactively, view https://console.cloud.google.com/net-security/securitypolicies/lb-security-policy/rules/1000/edit
Fixes #1758
<details>
</details>
Configured my test project with terraform apply
Manually changed settings in console, and tested that terraform apply apply un-did the changes.
Manually changed settings in console, made same settings in terraform config, and tested that apply did nothing.

Create placeholder IP blocking security policy

---

docs/devdesign/architecture.md

Remove my lucidchart - my subscription is no longer alive and I of course am not updating the diagram at that URL.
Note also that the architecture diagram has its own special license (still under a partial MIT license).  I'm happy to relicense if the other authors are as well.
Some missing things from the diagram include but are not limited to:
- The TerraForm work that has been done recently and how those tools have admin access to production
- The storage of a portion of the server logs in Belgium (while others appear to be global)
- The location (presumably in the US) of the members of the current team who will access the logs and user databases
- The load balancers/reverse proxies that may live in front of the app engine
- and other things I may not be aware of (I only looked …

Architecture diagram is not current

---

client/android/app/src/main/AndroidManifest.xml
client/ios/Podfile.lock
client/ios/Runner/Info.plist
client/lib/api/notifications.dart
client/lib/api/user_preferences.dart
client/lib/pages/onboarding/onboarding_page.dart
client/pubspec.lock
client/pubspec.yaml

Changes based on https://firebase.flutter.dev/docs/migration/
- onMessage* handlers
- Removed intent: `FLUTTER_NOTIFICATION_CLICK`
- Dependency changes:
```
firebase_core: ^0.5.2
firebase_crashlytics: ^0.2.3
firebase_messaging: ^8.0.0-dev.8
```
Local builds and CI. Still need to test notifications with the server.

FlutterFire Migration

---

server/terraform/README.md
server/terraform/main.tf
tools/terraform-fmt-validate.sh

- Add init to terraform-fmt-validate.sh script
- Add links to all top level projects
- **NOTE** never do `terraform apply` at top level, only individual projects
1. Added formatting error to staging project
1. Verify that `terraform validate .` in `server/terraform` missed the error
1. Added this code
1. Verified again that it caught the error

Terraform validate all projects

---

.github/workflows/static-content.yaml
server/README.md
tools/build-and-push-static-serving.sh
tools/deploy-production-static-serving.sh
tools/deploy-staging-static-serving.sh

- Rebuild scripts around the ProjectID
- Removed staging / prod specific scripts
- Support legacy mode for GitHub deploy of old staging server
Repeated runs of the scripts across different project and manually running expected GitHub workflow script.

Static Content deploy to use ProjectId

---

client/lib/api/content/content_loading.dart
client/lib/api/endpoints.dart
client/lib/main.dart
server/README.md

- "No Privacy" alert based on "prod" server or not
- Updates App Engine and Content endpoints
- No more direct usage of Storage Bucket direct URL
- Fixes #1781
```
flutter run --flavor prod
```
Checked:
- "No Privacy..." message not shown but shown for other flavors
- Fetched content successfully
- Discovered another issue that's orthogonal: #1799

Endpoints changed based on build flavor

---

server/terraform/README.md
server/terraform/modules/myhealth/variables.tf

Analytics Changes:
- Disallow ads personalization for all countries
- Disallow use of data across certain Google systems
- Document accepted policies
- Device only identity
- Partial fix for #1780
Other Changes:
- Regionalized Logs comment on moving to Switzerland
- Android build flavor upcoming PR #1789
- Repo location for `google-services.json` files
- Crashlytics correctly switches between Firebase projects
Manually applied to `who-mh-no-privacy` test account for Google Analytics (used for development servers only with no privacy warnings in the app).

Analytics improved privacy settings and documentation

---

SECURITY.md
server/bin/deploy-server.sh

Fixes #1799
Revert is tracked in #1804
```
server/bin/deploy-server.sh who-mh-hack
```

--ingress all

---

server/terraform/modules/http-load-balancer/main.tf
server/terraform/staging/main.tf

- staging-temp.whocoronavirus.org => staging.whocoronavirus.org
- Fixes #1810
```
cd server/terraform/staging
terraform apply
...
Error: Error when reading or editing ManagedSslCertificate: googleapi: Error 400: The ssl_certificate resource 'projects/who-mh-staging/global/sslCertificates/who-mh-staging-lb-ssl-cert-c1c03f3b' is already being used by 'projects/who-mh-staging/global/targetHttpsProxies/who-mh-staging-lb-https-proxy', resourceInUseByAnotherResource
terraform apply
...
Apply complete! Resources: 0 added, 0 changed, 2 destroyed.
```

Fix staging SSL cert

---

client/lib/api/content/content_loading.dart
client/lib/api/endpoints.dart
client/lib/main.dart

Short projectID in alert, e.g. "hack" or "staging"
Multiple build flavors, including hidden for "prod"

ProjectID in Alert

---

.github/workflows/client.yaml
client/README.md
client/lib/generated/build.dart
client/lib/pages/about_page.dart
docs/release/manual-build.md
tools/gen-client-buildinfo.sh

- Replaced by build flavors
- Remove "BUILT_AT" as it blocks reproducible build
- iOS CI build addition: `./tools/gen-client-buildinfo.sh`
CI + running `./tools/gen-client-buildinfo.sh`

DEVELOPMENT_ONLY deprecated

---

api/who/who.proto
client/lib/api/notifications.dart
client/lib/api/who_service.dart
client/lib/main.dart
client/lib/pages/onboarding/onboarding_page.dart
client/lib/pages/settings_page.dart
client/lib/proto/api/who/who.pb.dart
client/lib/proto/api/who/who.pbenum.dart
client/lib/proto/api/who/who.pbjson.dart
client/lib/proto/api/who/who.pbserver.dart
server/appengine/src/main/java/who/NotificationsManager.java
server/appengine/src/main/java/who/WhoServiceImpl.java

This change set includes Client and Server changes to obsolete putDeviceToken and putLocation in favor of new putNotificationSettings.
It also adds a tiny bit of debug logging on the server.
The behavior should be mostly the same as before in terms of when RPCs are fired. One  RPC is skipped: if the user has not selected a country, they will not be subscribed to notifications.
No true locking is present either client or server side at this time: it is possible for up to three (or more) requests to come in 'simulteanously', where the last one will win: getstats for a new user, and a putNotificationSettings if the response is taking some period of time. However, now that the initial 'firebase token plus no country' RPC is gone, it is highly unlikley for this to happen, as it would mean that …

WIP: Client race condition fixes (putLocation and putDeviceToken in single request )

---

server/appengine/build.gradle
server/appengine/src/main/java/who/WhoServletModule.java

Remove remote_api from server configuration. This should not be needed.
<details>
</details>
Opened in browser. Error message changed from "This request did not contain a necessary header" to a generic "Error: Not Found".

Remove remote_api

---

client/lib/api/content/content_store.dart
client/lib/api/stats_store.dart
client/lib/api/user_preferences.dart
client/lib/main.dart
client/lib/pages/onboarding/onboarding_page.dart

- OnboardingCompletedV2 repeats same process as in #1450
- Increasingly unwieldy but the safest approach since used previously
- `LegalCompletedTimestamp` recorded for facilitating new approach
- Fixes #1842
Repeated onboarding and fresh onboarding

Re-TOS and re-Onboard all users

---

client/lib/generated/intl/messages_en.dart
client/lib/generated/intl/messages_en_US.dart
client/lib/generated/intl/messages_fr.dart
client/lib/generated/intl/messages_fr_FR.dart
client/lib/generated/l10n.dart
client/lib/l10n/intl_en_US.arb
client/lib/l10n/intl_fr_FR.arb

- Possibly should redirect to who.int landing if not identified as iOS or Android user
- In that case, won't know what the appropriate app store link would be if any

whoapp.org/app => covid19app.who.int/app

---

server/appengine/src/main/java/who/Client.java
server/appengine/src/main/java/who/NotificationsManager.java
server/appengine/src/main/java/who/Topics.java
server/appengine/src/main/java/who/WhoServiceImpl.java

- Notification disabled implemented by setting token to zero
- `updateSubscriptions` on BE will unsubscribe all topics in that case
- Fixes #1857
- TODO: more testing
- Staging server and Android device
- Toggling on and off notifications
- Sending to both `ALL~LOCATION` and `ALL~LOCATION~US` topics

Respect Disable Notifications User Setting

---

client/lib/api/stats_store.dart

GetStats: Persist the country only on success.
Fixes #1858 
<details>
</details>
I have not yet tested this! Will do so later today.

GetStats: Persist the country only on success

---

server/appengine/src/main/java/who/Environment.java
server/appengine/src/main/java/who/RefreshCaseStatsServlet.java
server/appengine/src/test/java/who/RefreshCaseStatsServletTest.java
server/appengine/src/test/java/who/WhoTestSupport.java
server/appengine/src/test/resources/smaller-who-data.json

Make RefreshCaseStats testable and add a skeletal test.
* Refactor RefreshCastStatsServlet.
* Add RefreshCaseStatsServletTest
* Switch from deprecated JsonParse.parse to JsonParse.parseString.
* Removed n>100000 limit. (Not sure why it was added.)
* Make WhoTestSupport work w/that test.
* Fix bug in Environment with app engine appid shard.
n/a
Ran the new unit test and it passed. Verfiied that making the expected value something other than 2 causes it to fail.

Make RefreshCaseStats testable

---

server/appengine/src/main/java/who/RefreshCaseStatsServlet.java

Log URLs requested of ArcGIS when refreshing case stats.
This will help us debug issue #1876 . 
In the common scenario, we should see two requests to the server: one at offset zero, one at offset number-of-records (today that is resultOffset=84846). The second request will return no records.
In the scenario where the data on the arcgis server is in flux, it may return multiple requests. This log record will let us validate that. 
In some other scenarios, e.g. large amounts of data but stable, it might send multiple requests, but we are probably not yet seeing that.
<details>
</details>
Redeployed to my App Engine instance. Went to https://console.cloud.google.com/appengine/cronjobs and triggered a cron job. …

Log URLs requested of ArcGIS

---

server/appengine/src/main/java/who/RefreshCaseStatsServlet.java
server/appengine/src/test/java/who/RefreshCaseStatsServletTest.java
server/appengine/src/test/resources/smaller-who-data-earlier.json

The RefreshCaseStats cron task will now fail if it sees a second entry for a particular time and place.
This is most likley happening when the arcgis server returns some sort of strange result, perhaps a 'paginated' one which is really overlapping rather than paginated data. We also see missing data when this occurs, suggesting that this process should fail rather than ignore any duplicates.
Likely fix for issue #1876
Unit tests.
Pushed to my instance also and will watch.

Fail RefreshCaseStats on duplicate data

---

server/appengine/src/main/java/who/RefreshCaseStatsServlet.java
server/appengine/src/test/java/who/RefreshCaseStatsServletTest.java
server/appengine/src/test/resources/smaller-who-data-page-2.json
server/appengine/src/test/resources/smaller-who-data-partial-day.json
server/appengine/src/test/resources/smaller-who-data-partial-last-day.json
server/appengine/src/test/resources/smaller-who-data.json

WHO dashboard stats are updated throughout the day. Some countries
may report 0 for daily cases and deaths. The ArcGIS data response can't
distinguish between "zero cases" and "no data reported yet".
So this heuristic deals with that:
- Global Stats: sum all stats, not just partial stats on last day
- Country Stats: drop last day when likely "no data reported yet"
Fixes #1724
Fixes #1876

Stats Fix - Partial Last Day

---

server/appengine/src/main/java/who/RefreshCaseStatsServlet.java
server/appengine/src/test/java/who/RefreshCaseStatsServletTest.java

Case Stats update is rejected if:
- Global cases drop below prior value
- Global stats rise more than 5% + 30,000 since last update
- Skip checks for first case stats entry
Unit tests

Case Stats update rejected for unexpected change

---

server/appengine/src/main/java/who/Environment.java
server/appengine/src/main/java/who/RefreshCaseStatsServlet.java
server/appengine/src/test/java/who/RefreshCaseStatsServletTest.java

Allow direct request to the cron job only if the instance is running on dev_appserver.
Note that before it could be done on non - 'prod' instances of the app; this is better done in the Cloud Console Cron Job page by clicking 'run'. 
Before it could 'doGet' also simply be called e.g. in the test environment; if this is desirable, the method could probably be extracted out from doGet so doGet does a bit of authorization then the other code becomes testable.
<details>
</details>
Ran in dev_appserver and tested with a GET to the app.
Added unit test to verify it has been blocked.
Uploaded to my instance, tested with 'run cron' button and direct url fetch.

Cron job: Only allow direct requests on dev_appserver.

---

.github/workflows/server.yaml
.github/workflows/static-content.yaml

- `setup-gcloud` corrected from `@0.2.0` => `@v0.2.0`
- Based off this documentation:
https://cloud.google.com/blog/topics/developers-practitioners/deploying-serverless-platforms-github-actions
CI after merge

Fix Static Content and App Engine deploys scripts

---

client/lib/components/home_page_sections/home_page_recent_numbers.dart
docs/credits.yaml

Bugfix on Home Screen shows a blank animation for countries having 0 daily National Cases like Anguilla has zero cases.
Issue number #1860 
Modified the condition on home_page_recent_number.dart file
displayed zero cases for daily National cases instead of a blank animation
- Device  Redmi 8A
- OS: Android 9.0

Bugfix on Home Screen shows a blank animation for countries having 0 daily National  

---

.github/workflows/client.yaml
.github/workflows/server.yaml
.github/workflows/static-content.yaml
docs/devdesign/ci.md
tools/build-and-push-static-serving.sh

- Standardize on projectID usage
- Correct project id
- Remove deprecated code in push script
CI Push Static Content after merge

Fix Static Content CI Push

---

client/lib/components/recent_numbers_graph.dart

Partial Fix #1916
<details>
</details>

Shorten Date Format

---

client/lib/components/home_page_sections/home_page_recent_numbers.dart

Partial fix of #1916
<details>
</details>

Added country name to Homepage Stats + Switched to Totals

---

.github/workflows/policy-check.yaml

This linter has not had added value, however, it is blocking PRs with too many false positives for something that isn't profane.

Remove PolicyCheck

---

client/README.md
client/lib/api/who_service.dart
client/lib/main.dart
client/pubspec.lock
client/pubspec.yaml
client/test/firebase_test.dart
server/firestore.rules
server/functions/src/firestore_rules.spec.ts
server/functions/src/index.ts

Before this PR, we would update the client's FCM token by writing to the `putClientSettings` HTTPS endpoint. With this PR, we remove that intermediate API layer and write directly to Firestore.
We don't currently use the FCM token, so the main purposes of this PR are to...
1. Demonstrate how we'll perform direct Firestore access.
2. Demonstrate how to configure the app to use the local Firebase (Firestore) emulator.
3. Prepare the application for later use of the FCM token.
Closes #1973
N/A

feat(v2 backend): update FCM token directly in Firestore
